# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resonite_io/v1/camera.proto, resonite_io/v1/context_menu.proto, resonite_io/v1/dash.proto, resonite_io/v1/display.proto, resonite_io/v1/locomotion.proto, resonite_io/v1/microphone.proto, resonite_io/v1/session.proto, resonite_io/v1/speaker.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AudioFrame",
    "CameraBase",
    "CameraFrame",
    "CameraFrameFormat",
    "CameraStreamRequest",
    "CameraStub",
    "ContextMenuBase",
    "ContextMenuCloseRequest",
    "ContextMenuGetStateRequest",
    "ContextMenuHand",
    "ContextMenuHighlightRequest",
    "ContextMenuInvokeRequest",
    "ContextMenuItem",
    "ContextMenuOpenRequest",
    "ContextMenuState",
    "ContextMenuStub",
    "DashActionResult",
    "DashBase",
    "DashCloseRequest",
    "DashElement",
    "DashGetStateRequest",
    "DashGetTreeRequest",
    "DashHighlightRequest",
    "DashInvokeRequest",
    "DashListScreensRequest",
    "DashOpenRequest",
    "DashRect",
    "DashScreen",
    "DashScreenList",
    "DashScrollRequest",
    "DashSetScreenRequest",
    "DashState",
    "DashStub",
    "DashTree",
    "DisplayApplyResponse",
    "DisplayBase",
    "DisplayConfig",
    "DisplayGetRequest",
    "DisplayState",
    "DisplayStub",
    "LocomotionBase",
    "LocomotionCommand",
    "LocomotionDriveSummary",
    "LocomotionResetRequest",
    "LocomotionResetSummary",
    "LocomotionStub",
    "MicrophoneAudioFrame",
    "MicrophoneBase",
    "MicrophoneStreamSummary",
    "MicrophoneStub",
    "PingRequest",
    "PingResponse",
    "SessionBase",
    "SessionStub",
    "SpeakerBase",
    "SpeakerStreamRequest",
    "SpeakerStub",
)

from collections.abc import AsyncIterable, AsyncIterator, Iterable
from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class CameraFrameFormat(betterproto2.Enum):
    UNSPECIFIED = 0

    RGBA8 = 1
    """
    1 ピクセル 4 byte (R, G, B, A の順)、row 0 = 画像上端 (top-left origin)。
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CAMERA_FRAME_FORMAT_UNSPECIFIED",
            1: "CAMERA_FRAME_FORMAT_RGBA8",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CAMERA_FRAME_FORMAT_UNSPECIFIED": 0,
            "CAMERA_FRAME_FORMAT_RGBA8": 1,
        }


class ContextMenuHand(betterproto2.Enum):
    """
    操作対象の InteractionHandler (手) を指定する。
    """

    UNSPECIFIED = 0
    """
    未指定。サーバは desktop の primary hand (`InputInterface.PrimaryHand`) として扱う。
    """

    PRIMARY = 1
    """
    primary hand 明示 (UNSPECIFIED と同じ)。
    """

    LEFT = 2

    RIGHT = 3

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CONTEXT_MENU_HAND_UNSPECIFIED",
            1: "CONTEXT_MENU_HAND_PRIMARY",
            2: "CONTEXT_MENU_HAND_LEFT",
            3: "CONTEXT_MENU_HAND_RIGHT",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CONTEXT_MENU_HAND_UNSPECIFIED": 0,
            "CONTEXT_MENU_HAND_PRIMARY": 1,
            "CONTEXT_MENU_HAND_LEFT": 2,
            "CONTEXT_MENU_HAND_RIGHT": 3,
        }


@dataclass(eq=False, repr=False)
class AudioFrame(betterproto2.Message):
    """
    AudioFrame は意図して generic に保つ (Microphone proto から同じ message を
    import 再利用できる余地を残す)。

    samples の長さは `sample_count * 2 (channels) * 4 (float32 bytes)`。
    インターリーブ順は (L0, R0, L1, R1, ...)。
    """

    frame_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    """
    Bridge tap 内で monotonic に採番 (stream 開始から 0 で振り直す)。
    """

    unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    Bridge が tap で受信した時刻 (UTC ナノ秒、UnixNanosClock 由来)。
    engine 側の dspTime ではなく wall clock を採用 (Python 側の他モダリティと
    揃えるため)。
    """

    sample_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    インターリーブされた 1 チャネル分のサンプル数 (= samples.length / 8)。
    """

    samples: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    """
    float32 LE, interleaved L, R, L, R, ... (channels=2 固定)。
    """


default_message_pool.register_message("resonite_io.v1", "AudioFrame", AudioFrame)


@dataclass(eq=False, repr=False)
class CameraFrame(betterproto2.Message):
    """
    pixels の長さは RGBA8 時 width * height * 4。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    format: "CameraFrameFormat" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: CameraFrameFormat(0)
    )

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)

    frame_id: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)

    pixels: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)


default_message_pool.register_message("resonite_io.v1", "CameraFrame", CameraFrame)


@dataclass(eq=False, repr=False)
class CameraStreamRequest(betterproto2.Message):
    """
    width/height が 0 以下のときはサーバ既定 (640x480)、fps_limit が 0 以下のときは
    pacing 無し (best-effort native fps)。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    fps_limit: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "CameraStreamRequest", CameraStreamRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuCloseRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuCloseRequest", ContextMenuCloseRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuGetStateRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuGetStateRequest", ContextMenuGetStateRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuHighlightRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )

    index: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuHighlightRequest", ContextMenuHighlightRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuInvokeRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )

    index: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuInvokeRequest", ContextMenuInvokeRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuItem(betterproto2.Message):
    """
    radial メニュー上の 1 項目。
    """

    index: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    """
    列挙順 (ArcLayout 子順)。Highlight / Invoke はこの index を指定する。
    """

    label: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    項目ラベル (toggle 項目等で空文字のことがある)。
    """

    enabled: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    項目のボタンが有効か (`Button.Enabled`)。
    """

    has_icon: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    アイコン (sprite) を持つか (`ContextMenuItem.HasSprite`)。
    """

    color_r: "float" = betterproto2.field(5, betterproto2.TYPE_FLOAT)
    """
    項目色 (RGBA、各成分 0.0〜1.0)。
    """

    color_g: "float" = betterproto2.field(6, betterproto2.TYPE_FLOAT)

    color_b: "float" = betterproto2.field(7, betterproto2.TYPE_FLOAT)

    color_a: "float" = betterproto2.field(8, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuItem", ContextMenuItem
)


@dataclass(eq=False, repr=False)
class ContextMenuOpenRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuOpenRequest", ContextMenuOpenRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuState(betterproto2.Message):
    """
    現在のコンテキストメニューの状態スナップショット。
    """

    is_open: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    メニューが開いているか (`InteractionHandler.IsContextMenuOpen`)。
    """

    items: "list[ContextMenuItem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    開いている場合の項目一覧 (閉じているときは空)。
    """

    highlighted_index: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    ハイライト中の項目 index。無ければ -1。
    """


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuState", ContextMenuState
)


@dataclass(eq=False, repr=False)
class DashActionResult(betterproto2.Message):
    """
    状態変化系操作の結果。
    """

    ok: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    操作が適用できたか。
    """

    found: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    指定 ref_id の要素が解決できたか (false なら ok も false)。
    """

    ref_id: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    操作対象として解決した ref_id (echo back)。
    """

    detail: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    補足 (lock / 非 interactable / 未解決などの理由)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "DashActionResult", DashActionResult
)


@dataclass(eq=False, repr=False)
class DashCloseRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "DashCloseRequest", DashCloseRequest
)


@dataclass(eq=False, repr=False)
class DashElement(betterproto2.Message):
    """
    dash UI ツリーの 1 ノード。`ref_id` / `locale_key` が言語非依存の主キー。
    """

    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    `Slot.ReferenceID.ToString()`。Invoke / Highlight / Scroll はこの ref_id で解決する。
    """

    type: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    component 型名 ("Button" / "ScrollRect" / "Text" / "Image" 等)。
    """

    slot_name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    `Slot.Name` (author 設定。空のことがある)。
    """

    locale_key: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    `LocaleString.content` (isLocaleKey のときのみ。例 "Settings.Audio")。言語非依存。
    生文字列ラベル (localize 済み) しか無い要素では空。
    """

    label: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    表示テキスト (`Button.LabelText` 等。localize 済み。debug / 人間向け)。
    """

    enabled: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)
    """
    有効か (`Slot.IsActive` かつ component active)。
    """

    interactable: "bool" = betterproto2.field(7, betterproto2.TYPE_BOOL)
    """
    操作可能か (`IUIInteractable` かつ enabled)。
    """

    rect: "DashRect | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )
    """
    要素の矩形。
    """

    parent_ref_id: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)
    """
    親要素の ref_id (ツリー連結用。root は空)。
    """

    depth: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)
    """
    ツリー深さ (root = 0)。
    """


default_message_pool.register_message("resonite_io.v1", "DashElement", DashElement)


@dataclass(eq=False, repr=False)
class DashGetStateRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "DashGetStateRequest", DashGetStateRequest
)


@dataclass(eq=False, repr=False)
class DashGetTreeRequest(betterproto2.Message):
    interactable_only: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    true なら interactable な要素のみ返す。
    """

    root_ref_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    部分木の root に使う ref_id。空なら dash 全体。
    """


default_message_pool.register_message(
    "resonite_io.v1", "DashGetTreeRequest", DashGetTreeRequest
)


@dataclass(eq=False, repr=False)
class DashHighlightRequest(betterproto2.Message):
    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "resonite_io.v1", "DashHighlightRequest", DashHighlightRequest
)


@dataclass(eq=False, repr=False)
class DashInvokeRequest(betterproto2.Message):
    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message(
    "resonite_io.v1", "DashInvokeRequest", DashInvokeRequest
)


@dataclass(eq=False, repr=False)
class DashListScreensRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "DashListScreensRequest", DashListScreensRequest
)


@dataclass(eq=False, repr=False)
class DashOpenRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "DashOpenRequest", DashOpenRequest
)


@dataclass(eq=False, repr=False)
class DashRect(betterproto2.Message):
    """
    UI 要素の矩形。origin = 画面左上 (0,0)、x 右・y 下。
    is_screen_space=false の場合は canvas 空間座標 (screen pixel 逆投影が未確定な
    ときのフォールバック)。client は is_screen_space で解釈を切り替える。
    """

    x: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)

    y: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)

    width: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)

    height: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)

    is_screen_space: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)


default_message_pool.register_message("resonite_io.v1", "DashRect", DashRect)


@dataclass(eq=False, repr=False)
class DashScreen(betterproto2.Message):
    """
    dash 下部タブが切り替える 1 screen (`RadiantDashScreen`) のスナップショット。
    `key` (LocaleStringDriver key、例 "Dash.Screens.Worlds") と `ref_id` が言語非依存キー。
    """

    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    screen slot の `ReferenceID.ToString()`。SetScreen の exact 指定キー。
    """

    key: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    言語非依存の主キー。`LocaleHelper.GetLocalizedDriver(screen.Label)?.Key?.Value`。
    取得できない screen では空文字。
    """

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    `screen.Slot.Name` (例 "Worlds")。第 2 の言語非依存 ID。
    """

    label: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    `screen.Label.Value` (localize 済み表示テキスト。debug / 人間向け)。
    """

    is_current: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    """
    この screen が current screen か (`screen == dash.Dash.CurrentScreen.Target`)。
    """

    enabled: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)
    """
    遷移可能か (`screen.ScreenEnabled.Value`。例: ログアウト中の Contacts は false)。
    """


default_message_pool.register_message("resonite_io.v1", "DashScreen", DashScreen)


@dataclass(eq=False, repr=False)
class DashScreenList(betterproto2.Message):
    """
    `ListScreens` の戻り。dash の全 screen 一覧。
    """

    screens: "list[DashScreen]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "resonite_io.v1", "DashScreenList", DashScreenList
)


@dataclass(eq=False, repr=False)
class DashScrollRequest(betterproto2.Message):
    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    delta_x: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)

    delta_y: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "DashScrollRequest", DashScrollRequest
)


@dataclass(eq=False, repr=False)
class DashSetScreenRequest(betterproto2.Message):
    ref_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    exact 指定キー (screen slot の ReferenceID)。非空なら優先。
    """

    key: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    言語非依存キー (例 "Dash.Screens.Worlds")。ref_id が空なら使う。
    """


default_message_pool.register_message(
    "resonite_io.v1", "DashSetScreenRequest", DashSetScreenRequest
)


@dataclass(eq=False, repr=False)
class DashState(betterproto2.Message):
    """
    dash (userspace overlay) の開閉状態スナップショット。
    """

    is_open: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    dash が開いているか (`UserspaceRadiantDash.Open`)。
    """

    open_lerp: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)
    """
    開閉アニメーションの lerp [0.0, 1.0] (`UserspaceRadiantDash.OpenLerp`)。
    """


default_message_pool.register_message("resonite_io.v1", "DashState", DashState)


@dataclass(eq=False, repr=False)
class DashTree(betterproto2.Message):
    """
    dash UI ツリーのスナップショット。
    """

    elements: "list[DashElement]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    列挙された要素 (深さ優先順)。dash が閉じているときは空。
    """

    screen_width: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)
    """
    ポインタ座標空間 = 現在の window 解像度 (pixel)。grounding 用。
    """

    screen_height: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)


default_message_pool.register_message("resonite_io.v1", "DashTree", DashTree)


@dataclass(eq=False, repr=False)
class DisplayApplyResponse(betterproto2.Message):
    """
    Apply の placeholder response。`google.protobuf.Empty` を avoid して
    custom empty を採用するのは `DisplayGetRequest` と同じ pattern
    (リポジトリ内で `google/protobuf/*` への依存を増やさないため)。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "DisplayApplyResponse", DisplayApplyResponse
)


@dataclass(eq=False, repr=False)
class DisplayConfig(betterproto2.Message):
    """
    Apply で渡す設定値。0 / 空はサーバ側で「変更しない」と解釈される。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    0 なら変更しない。1 以上は新しい renderer 解像度の希望値。
    """

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    0.0 なら変更しない。1.0 以上は新しい Application.targetFrameRate。
    """


default_message_pool.register_message("resonite_io.v1", "DisplayConfig", DisplayConfig)


@dataclass(eq=False, repr=False)
class DisplayGetRequest(betterproto2.Message):
    """
    Get の placeholder request (将来 fields 追加に備える)。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "DisplayGetRequest", DisplayGetRequest
)


@dataclass(eq=False, repr=False)
class DisplayState(betterproto2.Message):
    """
    engine 側で実際に適用された後の現値。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message("resonite_io.v1", "DisplayState", DisplayState)


@dataclass(eq=False, repr=False)
class LocomotionCommand(betterproto2.Message):
    """
    クライアントからサーバへ送る制御コマンド。全 field は変化があった時だけ
    送れば mod 側 Bridge が engine update tick ごとに再注入する。
    """

    move_forward: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)
    """
    -1=back, +1=forward。視点方向 (fly/noclip では向いた方向、walk では水平)。
    """

    move_right: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)
    """
    -1=left, +1=right (strafe)。
    """

    move_up: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    -1=down, +1=up。**ワールド絶対**上下 (視点 pitch と独立)。
    SmoothLocomotion の Move に効き fly/noclip で上下移動、歩行系では engine が
    自動的に無視。proto3 wire default 0 = 中立 (velocity と違い 0 が単位元)。
    """

    yaw_rate: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)
    """
    Yaw angular rate, positive=right.
    """

    pitch_rate: "float" = betterproto2.field(5, betterproto2.TYPE_FLOAT)
    """
    Pitch angular rate, positive=up. Bridge は符号反転せず engine にそのまま
    渡す (decompile からは反転が必要に見えるが実機検証で逆挙動を確認、
    feedback_locomotion_external_input.md §2 参照)。
    """

    jump: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)
    """
    Space 相当の **pulse**。Bridge は受信した次 1 engine tick だけ apply し
    latch を下げる (consume-once)。client 側で false に戻す責務は無い。
    """

    velocity: "float" = betterproto2.field(7, betterproto2.TYPE_FLOAT)
    """
    Move に掛けるスカラー倍率。**単位元は 1.0** (通常歩行)。Python
    `LocomotionCmd.velocity` は default=1.0 を保証し、Bridge は proto.velocity
    を素のまま Move に掛ける (再解釈なし)。engine の
    `ScreenLocomotionDirection.FastMultiplier` (=2.0) 相当は 2.0 を明示する。

    注意: proto3 wire default は 0。raw proto を直接生成して velocity を設定
    しないと Move が 0 倍され停止する (convenience client なら default 1.0 で
    回避済み)。**ここが velocity セマンティクスの正典。**
    """

    crouch: "float" = betterproto2.field(8, betterproto2.TYPE_FLOAT)
    """
    Crouch 強度 [0..1]。
    """

    unix_nanos: "int" = betterproto2.field(9, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒)。受信側 latency 計測用、optional (0 で skip)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionCommand", LocomotionCommand
)


@dataclass(eq=False, repr=False)
class LocomotionDriveSummary(betterproto2.Message):
    """
    Drive RPC 完了時の summary。
    """

    received_count: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    正常に処理したコマンド数。
    """

    dropped_count: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    pending を上書きした (= latest-wins で drop した) 回数。
    現状の直列 ApplyAsync では常に 0。将来 non-blocking bridge へ拡張する hook。
    """

    unix_nanos: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionDriveSummary", LocomotionDriveSummary
)


@dataclass(eq=False, repr=False)
class LocomotionResetRequest(betterproto2.Message):
    """
    指定された field を中立値に戻す要求。**全 bool が false で送信された場合は
    全 reset** と Service 層で展開される (proto3 wire default = 0 で "未指定" と
    "全 false" を区別不能なため、Reset を呼んだ以上は全部戻す解釈に倒す)。
    部分 reset したい時は対象 field のみ true にする。
    """

    move: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    move_forward / move_right / move_up / velocity を中立 (0, 0, 0, 1.0) へ。
    """

    look: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    yaw_rate / pitch_rate を 0 へ。
    """

    crouch: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    crouch を 0 へ。
    """

    jump: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    未消費の jump pending を取り消す。
    """

    unix_nanos: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒)。Optional (0 で skip)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionResetRequest", LocomotionResetRequest
)


@dataclass(eq=False, repr=False)
class LocomotionResetSummary(betterproto2.Message):
    """
    Reset RPC 完了時の summary。Service が request を canonicalize した結果
    (全 false → 全 true 展開) をそのままエコーする。次の engine tick で
    Bridge が実際に該当 field を中立に戻す責務を負うため、本 summary は
    "canonicalize 後に有効だった reset 要求" を表すのみで、engine 側で実際に
    状態が変わったことの保証ではない。
    """

    move: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に move を reset する要求があったか。
    """

    look: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に look を reset する要求があったか。
    """

    crouch: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に crouch を reset する要求があったか。
    """

    jump: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に jump を reset する要求があったか。
    """

    unix_nanos: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionResetSummary", LocomotionResetSummary
)


@dataclass(eq=False, repr=False)
class MicrophoneAudioFrame(betterproto2.Message):
    """
    Python → server に送る音声 chunk。

    samples は `sample_count * 4 (float32 bytes)`。mono なので interleave なし。
    """

    frame_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    """
    Python クライアントが 0 から monotonic に採番。連続性検査 / 順序保証用。
    """

    unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒、time.time_ns())。latency 計測用。
    """

    sample_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    sample 数 (= samples.length / 4)。
    """

    samples: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    """
    float32 LE, mono (channel 数=1 固定)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "MicrophoneAudioFrame", MicrophoneAudioFrame
)


@dataclass(eq=False, repr=False)
class MicrophoneStreamSummary(betterproto2.Message):
    """
    StreamAudio RPC 完了時の summary。
    """

    received_frames: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    server が受信した frame 総数。
    """

    received_samples: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    server が受信した sample 総数 (= 各 frame の sample_count の合計)。
    """

    dropped_frames: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    Bridge 側で drop した frame 数 (ring buffer overflow など)。未実装時は 0。
    """

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "MicrophoneStreamSummary", MicrophoneStreamSummary
)


@dataclass(eq=False, repr=False)
class PingRequest(betterproto2.Message):
    """
    PingRequest はクライアントが任意のメッセージ文字列を送信する。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "PingRequest", PingRequest)


@dataclass(eq=False, repr=False)
class PingResponse(betterproto2.Message):
    """
    PingResponse はサーバが受信したメッセージをそのまま返し、サーバ側で測定した
    Unix epoch (ナノ秒) を付与する。クライアントは RTT の概算と clock skew の
    観測に利用できる。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    server_unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "PingResponse", PingResponse)


@dataclass(eq=False, repr=False)
class SpeakerStreamRequest(betterproto2.Message):
    """
    現状フィールドなし。将来 device 選択 (primary / streaming output) や
    開始時刻指定を入れる余地として message は保持する。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "SpeakerStreamRequest", SpeakerStreamRequest
)


class CameraStub(betterproto2_grpclib.ServiceStub):
    async def stream_frames(
        self,
        message: "CameraStreamRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[CameraFrame]":
        async for response in self._unary_stream(
            "/resonite_io.v1.Camera/StreamFrames",
            message,
            CameraFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class ContextMenuStub(betterproto2_grpclib.ServiceStub):
    async def open(
        self,
        message: "ContextMenuOpenRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        標準項目入りのコンテキストメニューを開く。開き終える (Opened) まで待ってから
        状態を返す。既に開いている場合は no-op で現状態を返す。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Open",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def close(
        self,
        message: "ContextMenuCloseRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        コンテキストメニューを閉じる。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Close",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_state(
        self,
        message: "ContextMenuGetStateRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        現在の状態 (開閉 / 項目一覧 / ハイライト) を取得する。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/GetState",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def highlight(
        self,
        message: "ContextMenuHighlightRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        指定 index の項目をハイライト (選択状態に) する。実行はしない。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Highlight",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def invoke(
        self,
        message: "ContextMenuInvokeRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        指定 index の項目のアクションを実行する。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Invoke",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class DashStub(betterproto2_grpclib.ServiceStub):
    async def open(
        self,
        message: "DashOpenRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashState":
        """
        dash (userspace overlay) を開く。既に開いていれば no-op で現状態を返す。
        """

        if message is None:
            message = DashOpenRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Dash/Open",
            message,
            DashState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def close(
        self,
        message: "DashCloseRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashState":
        """
        dash を閉じる。
        """

        if message is None:
            message = DashCloseRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Dash/Close",
            message,
            DashState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_state(
        self,
        message: "DashGetStateRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashState":
        """
        現在の dash 開閉状態を取得する。
        """

        if message is None:
            message = DashGetStateRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Dash/GetState",
            message,
            DashState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_tree(
        self,
        message: "DashGetTreeRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashTree":
        """
        現在開いている dash UI ツリーを列挙する。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Dash/GetTree",
            message,
            DashTree,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def invoke(
        self,
        message: "DashInvokeRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashActionResult":
        """
        指定 ref_id の要素のアクションを実行する (Button.SimulatePress 等)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Dash/Invoke",
            message,
            DashActionResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def highlight(
        self,
        message: "DashHighlightRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashActionResult":
        """
        指定 ref_id の要素をハイライト (hover) する。実行はしない。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Dash/Highlight",
            message,
            DashActionResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def scroll(
        self,
        message: "DashScrollRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashActionResult":
        """
        指定 ref_id の要素にスクロールを当てる。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Dash/Scroll",
            message,
            DashActionResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_screens(
        self,
        message: "DashListScreensRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashScreenList":
        """
        dash の全 screen を言語非依存キー付きで列挙する。dash が閉じていても列挙できる。
        """

        if message is None:
            message = DashListScreensRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Dash/ListScreens",
            message,
            DashScreenList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def set_screen(
        self,
        message: "DashSetScreenRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DashActionResult":
        """
        指定 screen (ref_id 優先、でなければ key) へ遷移する。両空は InvalidArgument。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Dash/SetScreen",
            message,
            DashActionResult,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class DisplayStub(betterproto2_grpclib.ServiceStub):
    async def apply(
        self,
        message: "DisplayConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayApplyResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Display/Apply",
            message,
            DisplayApplyResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get(
        self,
        message: "DisplayGetRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayState":
        if message is None:
            message = DisplayGetRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Display/Get",
            message,
            DisplayState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class LocomotionStub(betterproto2_grpclib.ServiceStub):
    async def drive(
        self,
        messages: "AsyncIterable[LocomotionCommand] | Iterable[LocomotionCommand]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御の client-streaming RPC。stream lifecycle と stateful
        repeater の規約は file header / `LocomotionCommand` 参照。
        """

        return await self._stream_unary(
            "/resonite_io.v1.Locomotion/Drive",
            messages,
            LocomotionCommand,
            LocomotionDriveSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reset(
        self,
        message: "LocomotionResetRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LocomotionResetSummary":
        """
        指定 field を中立値に戻す (Drive stream を中断しない unary)。全 bool
        が false なら全 reset (`LocomotionResetRequest` 参照)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Locomotion/Reset",
            message,
            LocomotionResetSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MicrophoneStub(betterproto2_grpclib.ServiceStub):
    async def stream_audio(
        self,
        messages: "AsyncIterable[MicrophoneAudioFrame] | Iterable[MicrophoneAudioFrame]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "MicrophoneStreamSummary":
        """
        Python が音声 frame を client-streaming で送信。Bridge は virtual
        AudioInput の ring buffer に append し、engine tick で WriteSamples
        経由で voice 配信ストリームに流す。

        disconnect / lifecycle:
          - `CompleteAsync` で graceful close → Bridge は ring buffer の残りを
            消化し続ける (再生中の余韻を切らない)。
          - UDS 切断 / 例外 cancel → Bridge が ring buffer を clear (RL/ロボティ
            クスの safety: client crash 時に古い音が残らない)。
        """

        return await self._stream_unary(
            "/resonite_io.v1.Microphone/StreamAudio",
            messages,
            MicrophoneAudioFrame,
            MicrophoneStreamSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SessionStub(betterproto2_grpclib.ServiceStub):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(
        self,
        message: "PingRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "PingResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Session/Ping",
            message,
            PingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SpeakerStub(betterproto2_grpclib.ServiceStub):
    async def stream_audio(
        self,
        message: "SpeakerStreamRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[AudioFrame]":
        """
        final mix を server-streaming で push 配信。Bridge が WASAPI audio thread
        からチャネルに push したものを engine 順序保証ありで流す。
        """

        if message is None:
            message = SpeakerStreamRequest()

        async for response in self._unary_stream(
            "/resonite_io.v1.Speaker/StreamAudio",
            message,
            AudioFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class CameraBase(betterproto2_grpclib.ServiceBase):
    async def stream_frames(
        self, message: "CameraStreamRequest"
    ) -> "AsyncIterator[CameraFrame]":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield CameraFrame()

    async def __rpc_stream_frames(
        self, stream: "grpclib.server.Stream[CameraStreamRequest, CameraFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_frames,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Camera/StreamFrames": grpclib.const.Handler(
                self.__rpc_stream_frames,
                grpclib.const.Cardinality.UNARY_STREAM,
                CameraStreamRequest,
                CameraFrame,
            ),
        }


class ContextMenuBase(betterproto2_grpclib.ServiceBase):
    async def open(self, message: "ContextMenuOpenRequest") -> "ContextMenuState":
        """
        標準項目入りのコンテキストメニューを開く。開き終える (Opened) まで待ってから
        状態を返す。既に開いている場合は no-op で現状態を返す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def close(self, message: "ContextMenuCloseRequest") -> "ContextMenuState":
        """
        コンテキストメニューを閉じる。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_state(
        self, message: "ContextMenuGetStateRequest"
    ) -> "ContextMenuState":
        """
        現在の状態 (開閉 / 項目一覧 / ハイライト) を取得する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def highlight(
        self, message: "ContextMenuHighlightRequest"
    ) -> "ContextMenuState":
        """
        指定 index の項目をハイライト (選択状態に) する。実行はしない。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def invoke(self, message: "ContextMenuInvokeRequest") -> "ContextMenuState":
        """
        指定 index の項目のアクションを実行する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_open(
        self, stream: "grpclib.server.Stream[ContextMenuOpenRequest, ContextMenuState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.open(request)
        await stream.send_message(response)

    async def __rpc_close(
        self, stream: "grpclib.server.Stream[ContextMenuCloseRequest, ContextMenuState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.close(request)
        await stream.send_message(response)

    async def __rpc_get_state(
        self,
        stream: "grpclib.server.Stream[ContextMenuGetStateRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_state(request)
        await stream.send_message(response)

    async def __rpc_highlight(
        self,
        stream: "grpclib.server.Stream[ContextMenuHighlightRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.highlight(request)
        await stream.send_message(response)

    async def __rpc_invoke(
        self,
        stream: "grpclib.server.Stream[ContextMenuInvokeRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.invoke(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.ContextMenu/Open": grpclib.const.Handler(
                self.__rpc_open,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuOpenRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Close": grpclib.const.Handler(
                self.__rpc_close,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuCloseRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/GetState": grpclib.const.Handler(
                self.__rpc_get_state,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuGetStateRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Highlight": grpclib.const.Handler(
                self.__rpc_highlight,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuHighlightRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Invoke": grpclib.const.Handler(
                self.__rpc_invoke,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuInvokeRequest,
                ContextMenuState,
            ),
        }


class DashBase(betterproto2_grpclib.ServiceBase):
    async def open(self, message: "DashOpenRequest") -> "DashState":
        """
        dash (userspace overlay) を開く。既に開いていれば no-op で現状態を返す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def close(self, message: "DashCloseRequest") -> "DashState":
        """
        dash を閉じる。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_state(self, message: "DashGetStateRequest") -> "DashState":
        """
        現在の dash 開閉状態を取得する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_tree(self, message: "DashGetTreeRequest") -> "DashTree":
        """
        現在開いている dash UI ツリーを列挙する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def invoke(self, message: "DashInvokeRequest") -> "DashActionResult":
        """
        指定 ref_id の要素のアクションを実行する (Button.SimulatePress 等)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def highlight(self, message: "DashHighlightRequest") -> "DashActionResult":
        """
        指定 ref_id の要素をハイライト (hover) する。実行はしない。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def scroll(self, message: "DashScrollRequest") -> "DashActionResult":
        """
        指定 ref_id の要素にスクロールを当てる。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_screens(self, message: "DashListScreensRequest") -> "DashScreenList":
        """
        dash の全 screen を言語非依存キー付きで列挙する。dash が閉じていても列挙できる。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def set_screen(self, message: "DashSetScreenRequest") -> "DashActionResult":
        """
        指定 screen (ref_id 優先、でなければ key) へ遷移する。両空は InvalidArgument。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_open(
        self, stream: "grpclib.server.Stream[DashOpenRequest, DashState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.open(request)
        await stream.send_message(response)

    async def __rpc_close(
        self, stream: "grpclib.server.Stream[DashCloseRequest, DashState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.close(request)
        await stream.send_message(response)

    async def __rpc_get_state(
        self, stream: "grpclib.server.Stream[DashGetStateRequest, DashState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_state(request)
        await stream.send_message(response)

    async def __rpc_get_tree(
        self, stream: "grpclib.server.Stream[DashGetTreeRequest, DashTree]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_tree(request)
        await stream.send_message(response)

    async def __rpc_invoke(
        self, stream: "grpclib.server.Stream[DashInvokeRequest, DashActionResult]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.invoke(request)
        await stream.send_message(response)

    async def __rpc_highlight(
        self, stream: "grpclib.server.Stream[DashHighlightRequest, DashActionResult]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.highlight(request)
        await stream.send_message(response)

    async def __rpc_scroll(
        self, stream: "grpclib.server.Stream[DashScrollRequest, DashActionResult]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.scroll(request)
        await stream.send_message(response)

    async def __rpc_list_screens(
        self, stream: "grpclib.server.Stream[DashListScreensRequest, DashScreenList]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_screens(request)
        await stream.send_message(response)

    async def __rpc_set_screen(
        self, stream: "grpclib.server.Stream[DashSetScreenRequest, DashActionResult]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.set_screen(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Dash/Open": grpclib.const.Handler(
                self.__rpc_open,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashOpenRequest,
                DashState,
            ),
            "/resonite_io.v1.Dash/Close": grpclib.const.Handler(
                self.__rpc_close,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashCloseRequest,
                DashState,
            ),
            "/resonite_io.v1.Dash/GetState": grpclib.const.Handler(
                self.__rpc_get_state,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashGetStateRequest,
                DashState,
            ),
            "/resonite_io.v1.Dash/GetTree": grpclib.const.Handler(
                self.__rpc_get_tree,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashGetTreeRequest,
                DashTree,
            ),
            "/resonite_io.v1.Dash/Invoke": grpclib.const.Handler(
                self.__rpc_invoke,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashInvokeRequest,
                DashActionResult,
            ),
            "/resonite_io.v1.Dash/Highlight": grpclib.const.Handler(
                self.__rpc_highlight,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashHighlightRequest,
                DashActionResult,
            ),
            "/resonite_io.v1.Dash/Scroll": grpclib.const.Handler(
                self.__rpc_scroll,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashScrollRequest,
                DashActionResult,
            ),
            "/resonite_io.v1.Dash/ListScreens": grpclib.const.Handler(
                self.__rpc_list_screens,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashListScreensRequest,
                DashScreenList,
            ),
            "/resonite_io.v1.Dash/SetScreen": grpclib.const.Handler(
                self.__rpc_set_screen,
                grpclib.const.Cardinality.UNARY_UNARY,
                DashSetScreenRequest,
                DashActionResult,
            ),
        }


class DisplayBase(betterproto2_grpclib.ServiceBase):
    async def apply(self, message: "DisplayConfig") -> "DisplayApplyResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get(self, message: "DisplayGetRequest") -> "DisplayState":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_apply(
        self, stream: "grpclib.server.Stream[DisplayConfig, DisplayApplyResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.apply(request)
        await stream.send_message(response)

    async def __rpc_get(
        self, stream: "grpclib.server.Stream[DisplayGetRequest, DisplayState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Display/Apply": grpclib.const.Handler(
                self.__rpc_apply,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayConfig,
                DisplayApplyResponse,
            ),
            "/resonite_io.v1.Display/Get": grpclib.const.Handler(
                self.__rpc_get,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayGetRequest,
                DisplayState,
            ),
        }


class LocomotionBase(betterproto2_grpclib.ServiceBase):
    async def drive(
        self, messages: "AsyncIterator[LocomotionCommand]"
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御の client-streaming RPC。stream lifecycle と stateful
        repeater の規約は file header / `LocomotionCommand` 参照。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reset(
        self, message: "LocomotionResetRequest"
    ) -> "LocomotionResetSummary":
        """
        指定 field を中立値に戻す (Drive stream を中断しない unary)。全 bool
        が false なら全 reset (`LocomotionResetRequest` 参照)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_drive(
        self, stream: "grpclib.server.Stream[LocomotionCommand, LocomotionDriveSummary]"
    ) -> None:
        request = stream.__aiter__()
        response = await self.drive(request)
        await stream.send_message(response)

    async def __rpc_reset(
        self,
        stream: "grpclib.server.Stream[LocomotionResetRequest, LocomotionResetSummary]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.reset(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Locomotion/Drive": grpclib.const.Handler(
                self.__rpc_drive,
                grpclib.const.Cardinality.STREAM_UNARY,
                LocomotionCommand,
                LocomotionDriveSummary,
            ),
            "/resonite_io.v1.Locomotion/Reset": grpclib.const.Handler(
                self.__rpc_reset,
                grpclib.const.Cardinality.UNARY_UNARY,
                LocomotionResetRequest,
                LocomotionResetSummary,
            ),
        }


class MicrophoneBase(betterproto2_grpclib.ServiceBase):
    async def stream_audio(
        self, messages: "AsyncIterator[MicrophoneAudioFrame]"
    ) -> "MicrophoneStreamSummary":
        """
        Python が音声 frame を client-streaming で送信。Bridge は virtual
        AudioInput の ring buffer に append し、engine tick で WriteSamples
        経由で voice 配信ストリームに流す。

        disconnect / lifecycle:
          - `CompleteAsync` で graceful close → Bridge は ring buffer の残りを
            消化し続ける (再生中の余韻を切らない)。
          - UDS 切断 / 例外 cancel → Bridge が ring buffer を clear (RL/ロボティ
            クスの safety: client crash 時に古い音が残らない)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_stream_audio(
        self,
        stream: "grpclib.server.Stream[MicrophoneAudioFrame, MicrophoneStreamSummary]",
    ) -> None:
        request = stream.__aiter__()
        response = await self.stream_audio(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Microphone/StreamAudio": grpclib.const.Handler(
                self.__rpc_stream_audio,
                grpclib.const.Cardinality.STREAM_UNARY,
                MicrophoneAudioFrame,
                MicrophoneStreamSummary,
            ),
        }


class SessionBase(betterproto2_grpclib.ServiceBase):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(self, message: "PingRequest") -> "PingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self, stream: "grpclib.server.Stream[PingRequest, PingResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.ping(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Session/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                PingRequest,
                PingResponse,
            ),
        }


class SpeakerBase(betterproto2_grpclib.ServiceBase):
    async def stream_audio(
        self, message: "SpeakerStreamRequest"
    ) -> "AsyncIterator[AudioFrame]":
        """
        final mix を server-streaming で push 配信。Bridge が WASAPI audio thread
        からチャネルに push したものを engine 順序保証ありで流す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield AudioFrame()

    async def __rpc_stream_audio(
        self, stream: "grpclib.server.Stream[SpeakerStreamRequest, AudioFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_audio,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Speaker/StreamAudio": grpclib.const.Handler(
                self.__rpc_stream_audio,
                grpclib.const.Cardinality.UNARY_STREAM,
                SpeakerStreamRequest,
                AudioFrame,
            ),
        }
