# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resonite_io/v1/camera.proto, resonite_io/v1/context_menu.proto, resonite_io/v1/display.proto, resonite_io/v1/locomotion.proto, resonite_io/v1/microphone.proto, resonite_io/v1/session.proto, resonite_io/v1/speaker.proto, resonite_io/v1/world.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AudioFrame",
    "CameraBase",
    "CameraFrame",
    "CameraFrameFormat",
    "CameraStreamRequest",
    "CameraStub",
    "ContextMenuBase",
    "ContextMenuCloseRequest",
    "ContextMenuGetStateRequest",
    "ContextMenuHand",
    "ContextMenuHighlightRequest",
    "ContextMenuInvokeRequest",
    "ContextMenuItem",
    "ContextMenuOpenRequest",
    "ContextMenuState",
    "ContextMenuStub",
    "DisplayApplyResponse",
    "DisplayBase",
    "DisplayConfig",
    "DisplayGetRequest",
    "DisplayState",
    "DisplayStub",
    "FetchThumbnailRequest",
    "FetchThumbnailResponse",
    "FocusRequest",
    "FocusResponse",
    "GetCurrentRequest",
    "GetCurrentResponse",
    "JoinRequest",
    "JoinResponse",
    "LeaveRequest",
    "LeaveResponse",
    "ListOpenWorldsRequest",
    "ListOpenWorldsResponse",
    "ListRecordsRequest",
    "ListRecordsResponse",
    "ListSessionsRequest",
    "ListSessionsResponse",
    "LocomotionBase",
    "LocomotionCommand",
    "LocomotionDriveSummary",
    "LocomotionResetRequest",
    "LocomotionResetSummary",
    "LocomotionStub",
    "MicrophoneAudioFrame",
    "MicrophoneBase",
    "MicrophoneStreamSummary",
    "MicrophoneStub",
    "OpenWorld",
    "PingRequest",
    "PingResponse",
    "RecordSort",
    "RecordSortDirection",
    "RecordSource",
    "SessionBase",
    "SessionFilter",
    "SessionStub",
    "SpeakerBase",
    "SpeakerStreamRequest",
    "SpeakerStub",
    "StartWorldRequest",
    "StartWorldResponse",
    "WorldBase",
    "WorldRecord",
    "WorldSession",
    "WorldStub",
)

from collections.abc import AsyncIterable, AsyncIterator, Iterable
from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class CameraFrameFormat(betterproto2.Enum):
    UNSPECIFIED = 0

    RGBA8 = 1
    """
    1 ピクセル 4 byte (R, G, B, A の順)、row 0 = 画像上端 (top-left origin)。
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CAMERA_FRAME_FORMAT_UNSPECIFIED",
            1: "CAMERA_FRAME_FORMAT_RGBA8",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CAMERA_FRAME_FORMAT_UNSPECIFIED": 0,
            "CAMERA_FRAME_FORMAT_RGBA8": 1,
        }


class ContextMenuHand(betterproto2.Enum):
    """
    操作対象の InteractionHandler (手) を指定する。
    """

    UNSPECIFIED = 0
    """
    未指定。サーバは desktop の primary hand (`InputInterface.PrimaryHand`) として扱う。
    """

    PRIMARY = 1
    """
    primary hand 明示 (UNSPECIFIED と同じ)。
    """

    LEFT = 2

    RIGHT = 3

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CONTEXT_MENU_HAND_UNSPECIFIED",
            1: "CONTEXT_MENU_HAND_PRIMARY",
            2: "CONTEXT_MENU_HAND_LEFT",
            3: "CONTEXT_MENU_HAND_RIGHT",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CONTEXT_MENU_HAND_UNSPECIFIED": 0,
            "CONTEXT_MENU_HAND_PRIMARY": 1,
            "CONTEXT_MENU_HAND_LEFT": 2,
            "CONTEXT_MENU_HAND_RIGHT": 3,
        }


class RecordSort(betterproto2.Enum):
    """
    レコード検索の並べ替え (SearchSortParameter にマップ)。
    UNSPECIFIED は既定で CREATION_DATE 扱い。
    """

    UNSPECIFIED = 0

    CREATION_DATE = 1

    LAST_UPDATE = 2

    FIRST_PUBLISH = 3

    TOTAL_VISITS = 4

    NAME = 5

    RANDOM = 6
    """
    「ランダム」タブ相当。
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "RECORD_SORT_UNSPECIFIED",
            1: "RECORD_SORT_CREATION_DATE",
            2: "RECORD_SORT_LAST_UPDATE",
            3: "RECORD_SORT_FIRST_PUBLISH",
            4: "RECORD_SORT_TOTAL_VISITS",
            5: "RECORD_SORT_NAME",
            6: "RECORD_SORT_RANDOM",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "RECORD_SORT_UNSPECIFIED": 0,
            "RECORD_SORT_CREATION_DATE": 1,
            "RECORD_SORT_LAST_UPDATE": 2,
            "RECORD_SORT_FIRST_PUBLISH": 3,
            "RECORD_SORT_TOTAL_VISITS": 4,
            "RECORD_SORT_NAME": 5,
            "RECORD_SORT_RANDOM": 6,
        }


class RecordSortDirection(betterproto2.Enum):
    """
    並べ替え方向 (SearchSortDirection にマップ)。
    UNSPECIFIED は既定で DESCENDING 扱い。
    """

    UNSPECIFIED = 0

    DESCENDING = 1

    ASCENDING = 2

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "RECORD_SORT_DIRECTION_UNSPECIFIED",
            1: "RECORD_SORT_DIRECTION_DESCENDING",
            2: "RECORD_SORT_DIRECTION_ASCENDING",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "RECORD_SORT_DIRECTION_UNSPECIFIED": 0,
            "RECORD_SORT_DIRECTION_DESCENDING": 1,
            "RECORD_SORT_DIRECTION_ASCENDING": 2,
        }


class RecordSource(betterproto2.Enum):
    """
    ワールドレコードのソース (左タブ相当)。UNSPECIFIED は既定で PUBLIC 扱い。
    """

    UNSPECIFIED = 0

    PUBLIC = 1

    FEATURED = 2

    OWN = 3

    GROUP = 4

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "RECORD_SOURCE_UNSPECIFIED",
            1: "RECORD_SOURCE_PUBLIC",
            2: "RECORD_SOURCE_FEATURED",
            3: "RECORD_SOURCE_OWN",
            4: "RECORD_SOURCE_GROUP",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "RECORD_SOURCE_UNSPECIFIED": 0,
            "RECORD_SOURCE_PUBLIC": 1,
            "RECORD_SOURCE_FEATURED": 2,
            "RECORD_SOURCE_OWN": 3,
            "RECORD_SOURCE_GROUP": 4,
        }


class SessionFilter(betterproto2.Enum):
    """
    ライブセッションの filter (左タブ相当)。UNSPECIFIED は「filter なし = 全件」。
    """

    UNSPECIFIED = 0

    FRIENDS = 1

    HEADLESS = 2

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "SESSION_FILTER_UNSPECIFIED",
            1: "SESSION_FILTER_FRIENDS",
            2: "SESSION_FILTER_HEADLESS",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "SESSION_FILTER_UNSPECIFIED": 0,
            "SESSION_FILTER_FRIENDS": 1,
            "SESSION_FILTER_HEADLESS": 2,
        }


@dataclass(eq=False, repr=False)
class AudioFrame(betterproto2.Message):
    """
    AudioFrame は意図して generic に保つ (Microphone proto から同じ message を
    import 再利用できる余地を残す)。

    samples の長さは `sample_count * 2 (channels) * 4 (float32 bytes)`。
    インターリーブ順は (L0, R0, L1, R1, ...)。
    """

    frame_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    """
    Bridge tap 内で monotonic に採番 (stream 開始から 0 で振り直す)。
    """

    unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    Bridge が tap で受信した時刻 (UTC ナノ秒、UnixNanosClock 由来)。
    engine 側の dspTime ではなく wall clock を採用 (Python 側の他モダリティと
    揃えるため)。
    """

    sample_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    インターリーブされた 1 チャネル分のサンプル数 (= samples.length / 8)。
    """

    samples: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    """
    float32 LE, interleaved L, R, L, R, ... (channels=2 固定)。
    """


default_message_pool.register_message("resonite_io.v1", "AudioFrame", AudioFrame)


@dataclass(eq=False, repr=False)
class CameraFrame(betterproto2.Message):
    """
    pixels の長さは RGBA8 時 width * height * 4。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    format: "CameraFrameFormat" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: CameraFrameFormat(0)
    )

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)

    frame_id: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)

    pixels: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)


default_message_pool.register_message("resonite_io.v1", "CameraFrame", CameraFrame)


@dataclass(eq=False, repr=False)
class CameraStreamRequest(betterproto2.Message):
    """
    width/height が 0 以下のときはサーバ既定 (640x480)、fps_limit が 0 以下のときは
    pacing 無し (best-effort native fps)。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    fps_limit: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "CameraStreamRequest", CameraStreamRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuCloseRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuCloseRequest", ContextMenuCloseRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuGetStateRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuGetStateRequest", ContextMenuGetStateRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuHighlightRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )

    index: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuHighlightRequest", ContextMenuHighlightRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuInvokeRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )

    index: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuInvokeRequest", ContextMenuInvokeRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuItem(betterproto2.Message):
    """
    radial メニュー上の 1 項目。
    """

    index: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    """
    列挙順 (ArcLayout 子順)。Highlight / Invoke はこの index を指定する。
    """

    label: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    項目ラベル (toggle 項目等で空文字のことがある)。
    """

    enabled: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    項目のボタンが有効か (`Button.Enabled`)。
    """

    has_icon: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    アイコン (sprite) を持つか (`ContextMenuItem.HasSprite`)。
    """

    color_r: "float" = betterproto2.field(5, betterproto2.TYPE_FLOAT)
    """
    項目色 (RGBA、各成分 0.0〜1.0)。
    """

    color_g: "float" = betterproto2.field(6, betterproto2.TYPE_FLOAT)

    color_b: "float" = betterproto2.field(7, betterproto2.TYPE_FLOAT)

    color_a: "float" = betterproto2.field(8, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuItem", ContextMenuItem
)


@dataclass(eq=False, repr=False)
class ContextMenuOpenRequest(betterproto2.Message):
    hand: "ContextMenuHand" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: ContextMenuHand(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuOpenRequest", ContextMenuOpenRequest
)


@dataclass(eq=False, repr=False)
class ContextMenuState(betterproto2.Message):
    """
    現在のコンテキストメニューの状態スナップショット。
    """

    is_open: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    メニューが開いているか (`InteractionHandler.IsContextMenuOpen`)。
    """

    items: "list[ContextMenuItem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )
    """
    開いている場合の項目一覧 (閉じているときは空)。
    """

    highlighted_index: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    ハイライト中の項目 index。無ければ -1。
    """


default_message_pool.register_message(
    "resonite_io.v1", "ContextMenuState", ContextMenuState
)


@dataclass(eq=False, repr=False)
class DisplayApplyResponse(betterproto2.Message):
    """
    Apply の placeholder response。`google.protobuf.Empty` を avoid して
    custom empty を採用するのは `DisplayGetRequest` と同じ pattern
    (リポジトリ内で `google/protobuf/*` への依存を増やさないため)。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "DisplayApplyResponse", DisplayApplyResponse
)


@dataclass(eq=False, repr=False)
class DisplayConfig(betterproto2.Message):
    """
    Apply で渡す設定値。0 / 空はサーバ側で「変更しない」と解釈される。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    0 なら変更しない。1 以上は新しい renderer 解像度の希望値。
    """

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    0.0 なら変更しない。1.0 以上は新しい Application.targetFrameRate。
    """


default_message_pool.register_message("resonite_io.v1", "DisplayConfig", DisplayConfig)


@dataclass(eq=False, repr=False)
class DisplayGetRequest(betterproto2.Message):
    """
    Get の placeholder request (将来 fields 追加に備える)。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "DisplayGetRequest", DisplayGetRequest
)


@dataclass(eq=False, repr=False)
class DisplayState(betterproto2.Message):
    """
    engine 側で実際に適用された後の現値。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message("resonite_io.v1", "DisplayState", DisplayState)


@dataclass(eq=False, repr=False)
class FetchThumbnailRequest(betterproto2.Message):
    uri: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    resdb:/// または https:// 形式のサムネ URI
    (WorldSession.thumbnail_url / WorldRecord.thumbnail_url の値)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "FetchThumbnailRequest", FetchThumbnailRequest
)


@dataclass(eq=False, repr=False)
class FetchThumbnailResponse(betterproto2.Message):
    data: "bytes" = betterproto2.field(1, betterproto2.TYPE_BYTES)

    content_type: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    MIME (例 "image/webp")。判定不能なら空。
    """


default_message_pool.register_message(
    "resonite_io.v1", "FetchThumbnailResponse", FetchThumbnailResponse
)


@dataclass(eq=False, repr=False)
class FocusRequest(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("resonite_io.v1", "FocusRequest", FocusRequest)


@dataclass(eq=False, repr=False)
class FocusResponse(betterproto2.Message):
    world: "OpenWorld | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("resonite_io.v1", "FocusResponse", FocusResponse)


@dataclass(eq=False, repr=False)
class GetCurrentRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "GetCurrentRequest", GetCurrentRequest
)


@dataclass(eq=False, repr=False)
class GetCurrentResponse(betterproto2.Message):
    world: "OpenWorld | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    has_world: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    userspace のみ (移動可能なワールドに focus していない) なら false。
    """


default_message_pool.register_message(
    "resonite_io.v1", "GetCurrentResponse", GetCurrentResponse
)


@dataclass(eq=False, repr=False)
class JoinRequest(betterproto2.Message):
    session_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    session_id で解決するか (優先)、session_url を直接指定するかのいずれか。
    """

    session_url: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    focus: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    join 後に focus するか (Userspace の AutoFocus に対応)。
    """


default_message_pool.register_message("resonite_io.v1", "JoinRequest", JoinRequest)


@dataclass(eq=False, repr=False)
class JoinResponse(betterproto2.Message):
    world: "OpenWorld | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("resonite_io.v1", "JoinResponse", JoinResponse)


@dataclass(eq=False, repr=False)
class LeaveRequest(betterproto2.Message):
    handle: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)


default_message_pool.register_message("resonite_io.v1", "LeaveRequest", LeaveRequest)


@dataclass(eq=False, repr=False)
class LeaveResponse(betterproto2.Message):
    pass


default_message_pool.register_message("resonite_io.v1", "LeaveResponse", LeaveResponse)


@dataclass(eq=False, repr=False)
class ListOpenWorldsRequest(betterproto2.Message):
    pass


default_message_pool.register_message(
    "resonite_io.v1", "ListOpenWorldsRequest", ListOpenWorldsRequest
)


@dataclass(eq=False, repr=False)
class ListOpenWorldsResponse(betterproto2.Message):
    worlds: "list[OpenWorld]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "resonite_io.v1", "ListOpenWorldsResponse", ListOpenWorldsResponse
)


@dataclass(eq=False, repr=False)
class ListRecordsRequest(betterproto2.Message):
    source: "RecordSource" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: RecordSource(0)
    )

    required_tags: "list[str]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )
    """
    カテゴリ tag 等 (例 "game" / "avatar")。AND 条件。
    """

    owner_id: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    GROUP / 特定 owner の OWN を引く場合の owner id。空なら OWN=ログインユーザ。
    """

    offset: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    """
    サーバ側ページング。
    """

    count: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    """
    取得件数。0 なら既定 (60)。
    """

    sort: "RecordSort" = betterproto2.field(
        6, betterproto2.TYPE_ENUM, default_factory=lambda: RecordSort(0)
    )

    sort_direction: "RecordSortDirection" = betterproto2.field(
        7, betterproto2.TYPE_ENUM, default_factory=lambda: RecordSortDirection(0)
    )


default_message_pool.register_message(
    "resonite_io.v1", "ListRecordsRequest", ListRecordsRequest
)


@dataclass(eq=False, repr=False)
class ListRecordsResponse(betterproto2.Message):
    records: "list[WorldRecord]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    has_more: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    まだ続きがあるか。
    """

    offset: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "resonite_io.v1", "ListRecordsResponse", ListRecordsResponse
)


@dataclass(eq=False, repr=False)
class ListSessionsRequest(betterproto2.Message):
    search: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    name 部分一致 (大文字小文字無視、client→mod 側でフィルタ)。空なら全件。
    """

    filter: "SessionFilter" = betterproto2.field(
        2, betterproto2.TYPE_ENUM, default_factory=lambda: SessionFilter(0)
    )

    min_active_users: "int" = betterproto2.field(3, betterproto2.TYPE_INT32)
    """
    0 なら下限なし。
    """

    page: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)
    """
    0-based ページ番号。
    """

    page_size: "int" = betterproto2.field(5, betterproto2.TYPE_UINT32)
    """
    1 ページあたり件数。0 なら無制限 (全件返す)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "ListSessionsRequest", ListSessionsRequest
)


@dataclass(eq=False, repr=False)
class ListSessionsResponse(betterproto2.Message):
    sessions: "list[WorldSession]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    total_count: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)
    """
    ページング前の総件数。
    """

    page: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)

    page_size: "int" = betterproto2.field(4, betterproto2.TYPE_UINT32)


default_message_pool.register_message(
    "resonite_io.v1", "ListSessionsResponse", ListSessionsResponse
)


@dataclass(eq=False, repr=False)
class LocomotionCommand(betterproto2.Message):
    """
    クライアントからサーバへ送る制御コマンド。全 field は変化があった時だけ
    送れば mod 側 Bridge が engine update tick ごとに再注入する。
    """

    move_forward: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)
    """
    -1=back, +1=forward。視点方向 (fly/noclip では向いた方向、walk では水平)。
    """

    move_right: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)
    """
    -1=left, +1=right (strafe)。
    """

    move_up: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    -1=down, +1=up。**ワールド絶対**上下 (視点 pitch と独立)。
    SmoothLocomotion の Move に効き fly/noclip で上下移動、歩行系では engine が
    自動的に無視。proto3 wire default 0 = 中立 (velocity と違い 0 が単位元)。
    """

    yaw_rate: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)
    """
    Yaw angular rate, positive=right.
    """

    pitch_rate: "float" = betterproto2.field(5, betterproto2.TYPE_FLOAT)
    """
    Pitch angular rate, positive=up. Bridge は符号反転せず engine にそのまま
    渡す (decompile からは反転が必要に見えるが実機検証で逆挙動を確認、
    feedback_locomotion_external_input.md §2 参照)。
    """

    jump: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)
    """
    Space 相当の **pulse**。Bridge は受信した次 1 engine tick だけ apply し
    latch を下げる (consume-once)。client 側で false に戻す責務は無い。
    """

    velocity: "float" = betterproto2.field(7, betterproto2.TYPE_FLOAT)
    """
    Move に掛けるスカラー倍率。**単位元は 1.0** (通常歩行)。Python
    `LocomotionCmd.velocity` は default=1.0 を保証し、Bridge は proto.velocity
    を素のまま Move に掛ける (再解釈なし)。engine の
    `ScreenLocomotionDirection.FastMultiplier` (=2.0) 相当は 2.0 を明示する。

    注意: proto3 wire default は 0。raw proto を直接生成して velocity を設定
    しないと Move が 0 倍され停止する (convenience client なら default 1.0 で
    回避済み)。**ここが velocity セマンティクスの正典。**
    """

    crouch: "float" = betterproto2.field(8, betterproto2.TYPE_FLOAT)
    """
    Crouch 強度 [0..1]。
    """

    unix_nanos: "int" = betterproto2.field(9, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒)。受信側 latency 計測用、optional (0 で skip)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionCommand", LocomotionCommand
)


@dataclass(eq=False, repr=False)
class LocomotionDriveSummary(betterproto2.Message):
    """
    Drive RPC 完了時の summary。
    """

    received_count: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    正常に処理したコマンド数。
    """

    dropped_count: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    pending を上書きした (= latest-wins で drop した) 回数。
    現状の直列 ApplyAsync では常に 0。将来 non-blocking bridge へ拡張する hook。
    """

    unix_nanos: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionDriveSummary", LocomotionDriveSummary
)


@dataclass(eq=False, repr=False)
class LocomotionResetRequest(betterproto2.Message):
    """
    指定された field を中立値に戻す要求。**全 bool が false で送信された場合は
    全 reset** と Service 層で展開される (proto3 wire default = 0 で "未指定" と
    "全 false" を区別不能なため、Reset を呼んだ以上は全部戻す解釈に倒す)。
    部分 reset したい時は対象 field のみ true にする。
    """

    move: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    move_forward / move_right / move_up / velocity を中立 (0, 0, 0, 1.0) へ。
    """

    look: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    yaw_rate / pitch_rate を 0 へ。
    """

    crouch: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    crouch を 0 へ。
    """

    jump: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    未消費の jump pending を取り消す。
    """

    unix_nanos: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒)。Optional (0 で skip)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionResetRequest", LocomotionResetRequest
)


@dataclass(eq=False, repr=False)
class LocomotionResetSummary(betterproto2.Message):
    """
    Reset RPC 完了時の summary。Service が request を canonicalize した結果
    (全 false → 全 true 展開) をそのままエコーする。次の engine tick で
    Bridge が実際に該当 field を中立に戻す責務を負うため、本 summary は
    "canonicalize 後に有効だった reset 要求" を表すのみで、engine 側で実際に
    状態が変わったことの保証ではない。
    """

    move: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に move を reset する要求があったか。
    """

    look: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に look を reset する要求があったか。
    """

    crouch: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に crouch を reset する要求があったか。
    """

    jump: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    canonicalize 後に jump を reset する要求があったか。
    """

    unix_nanos: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionResetSummary", LocomotionResetSummary
)


@dataclass(eq=False, repr=False)
class MicrophoneAudioFrame(betterproto2.Message):
    """
    Python → server に送る音声 chunk。

    samples は `sample_count * 4 (float32 bytes)`。mono なので interleave なし。
    """

    frame_id: "int" = betterproto2.field(1, betterproto2.TYPE_UINT64)
    """
    Python クライアントが 0 から monotonic に採番。連続性検査 / 順序保証用。
    """

    unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒、time.time_ns())。latency 計測用。
    """

    sample_count: "int" = betterproto2.field(3, betterproto2.TYPE_UINT32)
    """
    sample 数 (= samples.length / 4)。
    """

    samples: "bytes" = betterproto2.field(4, betterproto2.TYPE_BYTES)
    """
    float32 LE, mono (channel 数=1 固定)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "MicrophoneAudioFrame", MicrophoneAudioFrame
)


@dataclass(eq=False, repr=False)
class MicrophoneStreamSummary(betterproto2.Message):
    """
    StreamAudio RPC 完了時の summary。
    """

    received_frames: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    server が受信した frame 総数。
    """

    received_samples: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    server が受信した sample 総数 (= 各 frame の sample_count の合計)。
    """

    dropped_frames: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    Bridge 側で drop した frame 数 (ring buffer overflow など)。未実装時は 0。
    """

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "MicrophoneStreamSummary", MicrophoneStreamSummary
)


@dataclass(eq=False, repr=False)
class OpenWorld(betterproto2.Message):
    """
    ローカルに開いているワールド 1 件 (Nest で複数並びうる)。
    """

    handle: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    """
    World.LocalWorldHandle。Focus / Leave の識別子。
    """

    session_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    focused: "bool" = betterproto2.field(4, betterproto2.TYPE_BOOL)
    """
    WorldManager.FocusedWorld と一致するなら true。
    """

    user_count: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)

    access_level: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "OpenWorld", OpenWorld)


@dataclass(eq=False, repr=False)
class PingRequest(betterproto2.Message):
    """
    PingRequest はクライアントが任意のメッセージ文字列を送信する。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "PingRequest", PingRequest)


@dataclass(eq=False, repr=False)
class PingResponse(betterproto2.Message):
    """
    PingResponse はサーバが受信したメッセージをそのまま返し、サーバ側で測定した
    Unix epoch (ナノ秒) を付与する。クライアントは RTT の概算と clock skew の
    観測に利用できる。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    server_unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "PingResponse", PingResponse)


@dataclass(eq=False, repr=False)
class SpeakerStreamRequest(betterproto2.Message):
    """
    現状フィールドなし。将来 device 選択 (primary / streaming output) や
    開始時刻指定を入れる余地として message は保持する。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "SpeakerStreamRequest", SpeakerStreamRequest
)


@dataclass(eq=False, repr=False)
class StartWorldRequest(betterproto2.Message):
    record_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    owner_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    focus: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "resonite_io.v1", "StartWorldRequest", StartWorldRequest
)


@dataclass(eq=False, repr=False)
class StartWorldResponse(betterproto2.Message):
    world: "OpenWorld | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "resonite_io.v1", "StartWorldResponse", StartWorldResponse
)


@dataclass(eq=False, repr=False)
class WorldRecord(betterproto2.Message):
    """
    ワールドレコード 1 件の情報 (保存済みワールド / テンプレート)。
    """

    record_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    owner_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    description: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    thumbnail_url: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    """
    Record のサムネ URI をそのまま載せる (空もありうる)。
    """

    tags: "list[str]" = betterproto2.field(6, betterproto2.TYPE_STRING, repeated=True)

    record_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    """
    resrec:// 形式の record URI。
    """

    last_modification_unix_nanos: "int" = betterproto2.field(8, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "WorldRecord", WorldRecord)


@dataclass(eq=False, repr=False)
class WorldSession(betterproto2.Message):
    """
    ライブセッション 1 件の情報 (ブラウザのタイル相当)。
    """

    session_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    name: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    description: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)

    host_user_id: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)

    host_username: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)

    session_urls: "list[str]" = betterproto2.field(
        6, betterproto2.TYPE_STRING, repeated=True
    )
    """
    join 先 URI 群 (Join に session_id を渡せば mod 側で解決するため通常は参照のみ)。
    """

    thumbnail_url: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    """
    SessionInfo.ThumbnailUrl をそのまま載せる (空もありうる)。
    """

    joined_users: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)

    active_users: "int" = betterproto2.field(9, betterproto2.TYPE_INT32)

    maximum_users: "int" = betterproto2.field(10, betterproto2.TYPE_INT32)

    tags: "list[str]" = betterproto2.field(11, betterproto2.TYPE_STRING, repeated=True)

    access_level: "str" = betterproto2.field(12, betterproto2.TYPE_STRING)
    """
    SessionAccessLevel の enum 名 (例 "Anyone" / "ContactsPlus")。
    """

    headless_host: "bool" = betterproto2.field(13, betterproto2.TYPE_BOOL)

    mobile_friendly: "bool" = betterproto2.field(14, betterproto2.TYPE_BOOL)

    corresponding_world_id: "str" = betterproto2.field(15, betterproto2.TYPE_STRING)

    universe_id: "str" = betterproto2.field(16, betterproto2.TYPE_STRING)

    session_begin_unix_nanos: "int" = betterproto2.field(17, betterproto2.TYPE_INT64)

    last_update_unix_nanos: "int" = betterproto2.field(18, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "WorldSession", WorldSession)


class CameraStub(betterproto2_grpclib.ServiceStub):
    async def stream_frames(
        self,
        message: "CameraStreamRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[CameraFrame]":
        async for response in self._unary_stream(
            "/resonite_io.v1.Camera/StreamFrames",
            message,
            CameraFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class ContextMenuStub(betterproto2_grpclib.ServiceStub):
    async def open(
        self,
        message: "ContextMenuOpenRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        標準項目入りのコンテキストメニューを開く。開き終える (Opened) まで待ってから
        状態を返す。既に開いている場合は no-op で現状態を返す。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Open",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def close(
        self,
        message: "ContextMenuCloseRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        コンテキストメニューを閉じる。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Close",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_state(
        self,
        message: "ContextMenuGetStateRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        現在の状態 (開閉 / 項目一覧 / ハイライト) を取得する。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/GetState",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def highlight(
        self,
        message: "ContextMenuHighlightRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        指定 index の項目をハイライト (選択状態に) する。実行はしない。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Highlight",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def invoke(
        self,
        message: "ContextMenuInvokeRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ContextMenuState":
        """
        指定 index の項目のアクションを実行する。
        """

        return await self._unary_unary(
            "/resonite_io.v1.ContextMenu/Invoke",
            message,
            ContextMenuState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class DisplayStub(betterproto2_grpclib.ServiceStub):
    async def apply(
        self,
        message: "DisplayConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayApplyResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Display/Apply",
            message,
            DisplayApplyResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get(
        self,
        message: "DisplayGetRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayState":
        if message is None:
            message = DisplayGetRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Display/Get",
            message,
            DisplayState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class LocomotionStub(betterproto2_grpclib.ServiceStub):
    async def drive(
        self,
        messages: "AsyncIterable[LocomotionCommand] | Iterable[LocomotionCommand]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御の client-streaming RPC。stream lifecycle と stateful
        repeater の規約は file header / `LocomotionCommand` 参照。
        """

        return await self._stream_unary(
            "/resonite_io.v1.Locomotion/Drive",
            messages,
            LocomotionCommand,
            LocomotionDriveSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reset(
        self,
        message: "LocomotionResetRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LocomotionResetSummary":
        """
        指定 field を中立値に戻す (Drive stream を中断しない unary)。全 bool
        が false なら全 reset (`LocomotionResetRequest` 参照)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.Locomotion/Reset",
            message,
            LocomotionResetSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class MicrophoneStub(betterproto2_grpclib.ServiceStub):
    async def stream_audio(
        self,
        messages: "AsyncIterable[MicrophoneAudioFrame] | Iterable[MicrophoneAudioFrame]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "MicrophoneStreamSummary":
        """
        Python が音声 frame を client-streaming で送信。Bridge は virtual
        AudioInput の ring buffer に append し、engine tick で WriteSamples
        経由で voice 配信ストリームに流す。

        disconnect / lifecycle:
          - `CompleteAsync` で graceful close → Bridge は ring buffer の残りを
            消化し続ける (再生中の余韻を切らない)。
          - UDS 切断 / 例外 cancel → Bridge が ring buffer を clear (RL/ロボティ
            クスの safety: client crash 時に古い音が残らない)。
        """

        return await self._stream_unary(
            "/resonite_io.v1.Microphone/StreamAudio",
            messages,
            MicrophoneAudioFrame,
            MicrophoneStreamSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SessionStub(betterproto2_grpclib.ServiceStub):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(
        self,
        message: "PingRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "PingResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Session/Ping",
            message,
            PingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SpeakerStub(betterproto2_grpclib.ServiceStub):
    async def stream_audio(
        self,
        message: "SpeakerStreamRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[AudioFrame]":
        """
        final mix を server-streaming で push 配信。Bridge が WASAPI audio thread
        からチャネルに push したものを engine 順序保証ありで流す。
        """

        if message is None:
            message = SpeakerStreamRequest()

        async for response in self._unary_stream(
            "/resonite_io.v1.Speaker/StreamAudio",
            message,
            AudioFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class WorldStub(betterproto2_grpclib.ServiceStub):
    async def list_sessions(
        self,
        message: "ListSessionsRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ListSessionsResponse":
        """
        ライブセッション一覧。filter / 検索 / ページングは mod・Service 側で適用。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/ListSessions",
            message,
            ListSessionsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_records(
        self,
        message: "ListRecordsRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ListRecordsResponse":
        """
        ワールドレコード一覧。sort=RANDOM で「ランダム」タブ相当。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/ListRecords",
            message,
            ListRecordsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def join(
        self,
        message: "JoinRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "JoinResponse":
        """
        既存セッションへ join (Relation=Nest)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/Join",
            message,
            JoinResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def start_world(
        self,
        message: "StartWorldRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "StartWorldResponse":
        """
        ワールドレコードから新規セッションを起動 (Relation=Nest)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/StartWorld",
            message,
            StartWorldResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_open_worlds(
        self,
        message: "ListOpenWorldsRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "ListOpenWorldsResponse":
        """
        ローカルに開いているワールド一覧。
        """

        if message is None:
            message = ListOpenWorldsRequest()

        return await self._unary_unary(
            "/resonite_io.v1.World/ListOpenWorlds",
            message,
            ListOpenWorldsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def focus(
        self,
        message: "FocusRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "FocusResponse":
        """
        handle 指定でワールドを focus。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/Focus",
            message,
            FocusResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def leave(
        self,
        message: "LeaveRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LeaveResponse":
        """
        handle 指定でワールドから退出 (Userspace.LeaveSession)。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/Leave",
            message,
            LeaveResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_current(
        self,
        message: "GetCurrentRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "GetCurrentResponse":
        """
        現在 focus 中のワールド。
        """

        if message is None:
            message = GetCurrentRequest()

        return await self._unary_unary(
            "/resonite_io.v1.World/GetCurrent",
            message,
            GetCurrentResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def fetch_thumbnail(
        self,
        message: "FetchThumbnailRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "FetchThumbnailResponse":
        """
        サムネ URI (resdb:/// / https://) を解決して画像バイトを返す。
        """

        return await self._unary_unary(
            "/resonite_io.v1.World/FetchThumbnail",
            message,
            FetchThumbnailResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CameraBase(betterproto2_grpclib.ServiceBase):
    async def stream_frames(
        self, message: "CameraStreamRequest"
    ) -> "AsyncIterator[CameraFrame]":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield CameraFrame()

    async def __rpc_stream_frames(
        self, stream: "grpclib.server.Stream[CameraStreamRequest, CameraFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_frames,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Camera/StreamFrames": grpclib.const.Handler(
                self.__rpc_stream_frames,
                grpclib.const.Cardinality.UNARY_STREAM,
                CameraStreamRequest,
                CameraFrame,
            ),
        }


class ContextMenuBase(betterproto2_grpclib.ServiceBase):
    async def open(self, message: "ContextMenuOpenRequest") -> "ContextMenuState":
        """
        標準項目入りのコンテキストメニューを開く。開き終える (Opened) まで待ってから
        状態を返す。既に開いている場合は no-op で現状態を返す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def close(self, message: "ContextMenuCloseRequest") -> "ContextMenuState":
        """
        コンテキストメニューを閉じる。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_state(
        self, message: "ContextMenuGetStateRequest"
    ) -> "ContextMenuState":
        """
        現在の状態 (開閉 / 項目一覧 / ハイライト) を取得する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def highlight(
        self, message: "ContextMenuHighlightRequest"
    ) -> "ContextMenuState":
        """
        指定 index の項目をハイライト (選択状態に) する。実行はしない。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def invoke(self, message: "ContextMenuInvokeRequest") -> "ContextMenuState":
        """
        指定 index の項目のアクションを実行する。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_open(
        self, stream: "grpclib.server.Stream[ContextMenuOpenRequest, ContextMenuState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.open(request)
        await stream.send_message(response)

    async def __rpc_close(
        self, stream: "grpclib.server.Stream[ContextMenuCloseRequest, ContextMenuState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.close(request)
        await stream.send_message(response)

    async def __rpc_get_state(
        self,
        stream: "grpclib.server.Stream[ContextMenuGetStateRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_state(request)
        await stream.send_message(response)

    async def __rpc_highlight(
        self,
        stream: "grpclib.server.Stream[ContextMenuHighlightRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.highlight(request)
        await stream.send_message(response)

    async def __rpc_invoke(
        self,
        stream: "grpclib.server.Stream[ContextMenuInvokeRequest, ContextMenuState]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.invoke(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.ContextMenu/Open": grpclib.const.Handler(
                self.__rpc_open,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuOpenRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Close": grpclib.const.Handler(
                self.__rpc_close,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuCloseRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/GetState": grpclib.const.Handler(
                self.__rpc_get_state,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuGetStateRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Highlight": grpclib.const.Handler(
                self.__rpc_highlight,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuHighlightRequest,
                ContextMenuState,
            ),
            "/resonite_io.v1.ContextMenu/Invoke": grpclib.const.Handler(
                self.__rpc_invoke,
                grpclib.const.Cardinality.UNARY_UNARY,
                ContextMenuInvokeRequest,
                ContextMenuState,
            ),
        }


class DisplayBase(betterproto2_grpclib.ServiceBase):
    async def apply(self, message: "DisplayConfig") -> "DisplayApplyResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get(self, message: "DisplayGetRequest") -> "DisplayState":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_apply(
        self, stream: "grpclib.server.Stream[DisplayConfig, DisplayApplyResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.apply(request)
        await stream.send_message(response)

    async def __rpc_get(
        self, stream: "grpclib.server.Stream[DisplayGetRequest, DisplayState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Display/Apply": grpclib.const.Handler(
                self.__rpc_apply,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayConfig,
                DisplayApplyResponse,
            ),
            "/resonite_io.v1.Display/Get": grpclib.const.Handler(
                self.__rpc_get,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayGetRequest,
                DisplayState,
            ),
        }


class LocomotionBase(betterproto2_grpclib.ServiceBase):
    async def drive(
        self, messages: "AsyncIterator[LocomotionCommand]"
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御の client-streaming RPC。stream lifecycle と stateful
        repeater の規約は file header / `LocomotionCommand` 参照。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reset(
        self, message: "LocomotionResetRequest"
    ) -> "LocomotionResetSummary":
        """
        指定 field を中立値に戻す (Drive stream を中断しない unary)。全 bool
        が false なら全 reset (`LocomotionResetRequest` 参照)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_drive(
        self, stream: "grpclib.server.Stream[LocomotionCommand, LocomotionDriveSummary]"
    ) -> None:
        request = stream.__aiter__()
        response = await self.drive(request)
        await stream.send_message(response)

    async def __rpc_reset(
        self,
        stream: "grpclib.server.Stream[LocomotionResetRequest, LocomotionResetSummary]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.reset(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Locomotion/Drive": grpclib.const.Handler(
                self.__rpc_drive,
                grpclib.const.Cardinality.STREAM_UNARY,
                LocomotionCommand,
                LocomotionDriveSummary,
            ),
            "/resonite_io.v1.Locomotion/Reset": grpclib.const.Handler(
                self.__rpc_reset,
                grpclib.const.Cardinality.UNARY_UNARY,
                LocomotionResetRequest,
                LocomotionResetSummary,
            ),
        }


class MicrophoneBase(betterproto2_grpclib.ServiceBase):
    async def stream_audio(
        self, messages: "AsyncIterator[MicrophoneAudioFrame]"
    ) -> "MicrophoneStreamSummary":
        """
        Python が音声 frame を client-streaming で送信。Bridge は virtual
        AudioInput の ring buffer に append し、engine tick で WriteSamples
        経由で voice 配信ストリームに流す。

        disconnect / lifecycle:
          - `CompleteAsync` で graceful close → Bridge は ring buffer の残りを
            消化し続ける (再生中の余韻を切らない)。
          - UDS 切断 / 例外 cancel → Bridge が ring buffer を clear (RL/ロボティ
            クスの safety: client crash 時に古い音が残らない)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_stream_audio(
        self,
        stream: "grpclib.server.Stream[MicrophoneAudioFrame, MicrophoneStreamSummary]",
    ) -> None:
        request = stream.__aiter__()
        response = await self.stream_audio(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Microphone/StreamAudio": grpclib.const.Handler(
                self.__rpc_stream_audio,
                grpclib.const.Cardinality.STREAM_UNARY,
                MicrophoneAudioFrame,
                MicrophoneStreamSummary,
            ),
        }


class SessionBase(betterproto2_grpclib.ServiceBase):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(self, message: "PingRequest") -> "PingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self, stream: "grpclib.server.Stream[PingRequest, PingResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.ping(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Session/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                PingRequest,
                PingResponse,
            ),
        }


class SpeakerBase(betterproto2_grpclib.ServiceBase):
    async def stream_audio(
        self, message: "SpeakerStreamRequest"
    ) -> "AsyncIterator[AudioFrame]":
        """
        final mix を server-streaming で push 配信。Bridge が WASAPI audio thread
        からチャネルに push したものを engine 順序保証ありで流す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield AudioFrame()

    async def __rpc_stream_audio(
        self, stream: "grpclib.server.Stream[SpeakerStreamRequest, AudioFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_audio,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Speaker/StreamAudio": grpclib.const.Handler(
                self.__rpc_stream_audio,
                grpclib.const.Cardinality.UNARY_STREAM,
                SpeakerStreamRequest,
                AudioFrame,
            ),
        }


class WorldBase(betterproto2_grpclib.ServiceBase):
    async def list_sessions(
        self, message: "ListSessionsRequest"
    ) -> "ListSessionsResponse":
        """
        ライブセッション一覧。filter / 検索 / ページングは mod・Service 側で適用。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_records(
        self, message: "ListRecordsRequest"
    ) -> "ListRecordsResponse":
        """
        ワールドレコード一覧。sort=RANDOM で「ランダム」タブ相当。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def join(self, message: "JoinRequest") -> "JoinResponse":
        """
        既存セッションへ join (Relation=Nest)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def start_world(self, message: "StartWorldRequest") -> "StartWorldResponse":
        """
        ワールドレコードから新規セッションを起動 (Relation=Nest)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_open_worlds(
        self, message: "ListOpenWorldsRequest"
    ) -> "ListOpenWorldsResponse":
        """
        ローカルに開いているワールド一覧。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def focus(self, message: "FocusRequest") -> "FocusResponse":
        """
        handle 指定でワールドを focus。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def leave(self, message: "LeaveRequest") -> "LeaveResponse":
        """
        handle 指定でワールドから退出 (Userspace.LeaveSession)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_current(self, message: "GetCurrentRequest") -> "GetCurrentResponse":
        """
        現在 focus 中のワールド。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def fetch_thumbnail(
        self, message: "FetchThumbnailRequest"
    ) -> "FetchThumbnailResponse":
        """
        サムネ URI (resdb:/// / https://) を解決して画像バイトを返す。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_list_sessions(
        self, stream: "grpclib.server.Stream[ListSessionsRequest, ListSessionsResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_sessions(request)
        await stream.send_message(response)

    async def __rpc_list_records(
        self, stream: "grpclib.server.Stream[ListRecordsRequest, ListRecordsResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_records(request)
        await stream.send_message(response)

    async def __rpc_join(
        self, stream: "grpclib.server.Stream[JoinRequest, JoinResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.join(request)
        await stream.send_message(response)

    async def __rpc_start_world(
        self, stream: "grpclib.server.Stream[StartWorldRequest, StartWorldResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.start_world(request)
        await stream.send_message(response)

    async def __rpc_list_open_worlds(
        self,
        stream: "grpclib.server.Stream[ListOpenWorldsRequest, ListOpenWorldsResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.list_open_worlds(request)
        await stream.send_message(response)

    async def __rpc_focus(
        self, stream: "grpclib.server.Stream[FocusRequest, FocusResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.focus(request)
        await stream.send_message(response)

    async def __rpc_leave(
        self, stream: "grpclib.server.Stream[LeaveRequest, LeaveResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.leave(request)
        await stream.send_message(response)

    async def __rpc_get_current(
        self, stream: "grpclib.server.Stream[GetCurrentRequest, GetCurrentResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get_current(request)
        await stream.send_message(response)

    async def __rpc_fetch_thumbnail(
        self,
        stream: "grpclib.server.Stream[FetchThumbnailRequest, FetchThumbnailResponse]",
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.fetch_thumbnail(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.World/ListSessions": grpclib.const.Handler(
                self.__rpc_list_sessions,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListSessionsRequest,
                ListSessionsResponse,
            ),
            "/resonite_io.v1.World/ListRecords": grpclib.const.Handler(
                self.__rpc_list_records,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRecordsRequest,
                ListRecordsResponse,
            ),
            "/resonite_io.v1.World/Join": grpclib.const.Handler(
                self.__rpc_join,
                grpclib.const.Cardinality.UNARY_UNARY,
                JoinRequest,
                JoinResponse,
            ),
            "/resonite_io.v1.World/StartWorld": grpclib.const.Handler(
                self.__rpc_start_world,
                grpclib.const.Cardinality.UNARY_UNARY,
                StartWorldRequest,
                StartWorldResponse,
            ),
            "/resonite_io.v1.World/ListOpenWorlds": grpclib.const.Handler(
                self.__rpc_list_open_worlds,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListOpenWorldsRequest,
                ListOpenWorldsResponse,
            ),
            "/resonite_io.v1.World/Focus": grpclib.const.Handler(
                self.__rpc_focus,
                grpclib.const.Cardinality.UNARY_UNARY,
                FocusRequest,
                FocusResponse,
            ),
            "/resonite_io.v1.World/Leave": grpclib.const.Handler(
                self.__rpc_leave,
                grpclib.const.Cardinality.UNARY_UNARY,
                LeaveRequest,
                LeaveResponse,
            ),
            "/resonite_io.v1.World/GetCurrent": grpclib.const.Handler(
                self.__rpc_get_current,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetCurrentRequest,
                GetCurrentResponse,
            ),
            "/resonite_io.v1.World/FetchThumbnail": grpclib.const.Handler(
                self.__rpc_fetch_thumbnail,
                grpclib.const.Cardinality.UNARY_UNARY,
                FetchThumbnailRequest,
                FetchThumbnailResponse,
            ),
        }
