# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resonite_io/v1/camera.proto, resonite_io/v1/display.proto, resonite_io/v1/locomotion.proto, resonite_io/v1/session.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CameraBase",
    "CameraFrame",
    "CameraFrameFormat",
    "CameraStreamRequest",
    "CameraStub",
    "DisplayBase",
    "DisplayConfig",
    "DisplayGetRequest",
    "DisplayState",
    "DisplayStub",
    "LocomotionBase",
    "LocomotionCommand",
    "LocomotionDriveSummary",
    "LocomotionStub",
    "PingRequest",
    "PingResponse",
    "SessionBase",
    "SessionStub",
)

from collections.abc import AsyncIterable, AsyncIterator, Iterable
from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class CameraFrameFormat(betterproto2.Enum):
    UNSPECIFIED = 0

    RGBA8 = 1
    """
    1 ピクセル 4 byte (R, G, B, A の順)、row 0 = 画像上端 (top-left origin)。
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CAMERA_FRAME_FORMAT_UNSPECIFIED",
            1: "CAMERA_FRAME_FORMAT_RGBA8",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CAMERA_FRAME_FORMAT_UNSPECIFIED": 0,
            "CAMERA_FRAME_FORMAT_RGBA8": 1,
        }


@dataclass(eq=False, repr=False)
class CameraFrame(betterproto2.Message):
    """
    pixels の長さは RGBA8 時 width * height * 4。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    format: "CameraFrameFormat" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: CameraFrameFormat(0)
    )

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)

    frame_id: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)

    pixels: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)


default_message_pool.register_message("resonite_io.v1", "CameraFrame", CameraFrame)


@dataclass(eq=False, repr=False)
class CameraStreamRequest(betterproto2.Message):
    """
    width/height が 0 以下のときはサーバ既定 (640x480)、fps_limit が 0 以下のときは
    pacing 無し (best-effort native fps)。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    fps_limit: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "CameraStreamRequest", CameraStreamRequest
)


@dataclass(eq=False, repr=False)
class DisplayConfig(betterproto2.Message):
    """
    Apply で渡す設定値。0 / 空はサーバ側で「変更しない」と解釈される。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)
    """
    0 なら変更しない。1 以上は新しい renderer 解像度の希望値。
    """

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    0.0 なら変更しない。1.0 以上は新しい Application.targetFrameRate。
    """


default_message_pool.register_message("resonite_io.v1", "DisplayConfig", DisplayConfig)


@dataclass(eq=False, repr=False)
class DisplayGetRequest(betterproto2.Message):
    """
    Get の placeholder request (将来 fields 追加に備える)。
    """

    pass


default_message_pool.register_message(
    "resonite_io.v1", "DisplayGetRequest", DisplayGetRequest
)


@dataclass(eq=False, repr=False)
class DisplayState(betterproto2.Message):
    """
    engine 側で実際に適用された後の現値。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_UINT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_UINT32)

    max_fps: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message("resonite_io.v1", "DisplayState", DisplayState)


@dataclass(eq=False, repr=False)
class LocomotionCommand(betterproto2.Message):
    """
    クライアントからサーバへ毎フレーム送る制御コマンド。全 field optional
    (proto3 default = 0 = neutral)。
    """

    move_x: "float" = betterproto2.field(1, betterproto2.TYPE_FLOAT)
    """
    Strafe input. -1.0 = left, 1.0 = right. SmoothLocomotionInputs.Move.x へ。
    """

    move_y: "float" = betterproto2.field(2, betterproto2.TYPE_FLOAT)
    """
    Forward input. -1.0 = backward, 1.0 = forward. SmoothLocomotionInputs.Move.z へ。
    """

    yaw_rate: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)
    """
    Yaw angular rate. positive = turn right. ScreenCameraInputs.Look.x へ。
    """

    pitch_rate: "float" = betterproto2.field(4, betterproto2.TYPE_FLOAT)
    """
    Pitch angular rate. positive = look up. Bridge が符号反転して
    ScreenCameraInputs.Look.y へ (engine が _verticalAngle -= y で反転するため)。
    """

    jump: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)
    """
    Space 相当。true で SmoothLocomotionInputs.Jump.ExternalInput=true (OR-merge)。
    """

    sprint: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)
    """
    Shift 相当。true のとき Bridge 内で Move.x/z を sprint_multiplier 倍する。
    """

    crouch: "float" = betterproto2.field(7, betterproto2.TYPE_FLOAT)
    """
    Crouch 強度 [0..1]。HeadInputs.Crouch.ExternalInput にそのまま流す。
    """

    sprint_multiplier: "float" = betterproto2.field(8, betterproto2.TYPE_FLOAT)
    """
    sprint=true のときに適用する Move 倍率。0 (proto3 default) は「server 既定 2.0」と
    解釈、>0 は override。engine の ScreenLocomotionDirection.FastMultiplier (=2.0)
    を ExternalInput 経路で再現する用途。
    """

    unix_nanos: "int" = betterproto2.field(9, betterproto2.TYPE_INT64)
    """
    クライアント送信時刻 (UTC ナノ秒)。受信側 latency 計測用、optional (0 で skip)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionCommand", LocomotionCommand
)


@dataclass(eq=False, repr=False)
class LocomotionDriveSummary(betterproto2.Message):
    """
    Drive RPC 完了時の summary。
    """

    received_count: "int" = betterproto2.field(1, betterproto2.TYPE_INT64)
    """
    正常に処理したコマンド数。
    """

    dropped_count: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)
    """
    pending を上書きした (= latest-wins で drop した) 回数。
    現状の直列 ApplyAsync では常に 0。将来 non-blocking bridge へ拡張する hook。
    """

    unix_nanos: "int" = betterproto2.field(3, betterproto2.TYPE_INT64)
    """
    サーバ完了時刻 (UTC ナノ秒)。
    """


default_message_pool.register_message(
    "resonite_io.v1", "LocomotionDriveSummary", LocomotionDriveSummary
)


@dataclass(eq=False, repr=False)
class PingRequest(betterproto2.Message):
    """
    PingRequest はクライアントが任意のメッセージ文字列を送信する。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "PingRequest", PingRequest)


@dataclass(eq=False, repr=False)
class PingResponse(betterproto2.Message):
    """
    PingResponse はサーバが受信したメッセージをそのまま返し、サーバ側で測定した
    Unix epoch (ナノ秒) を付与する。クライアントは RTT の概算と clock skew の
    観測に利用できる。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    server_unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "PingResponse", PingResponse)


class CameraStub(betterproto2_grpclib.ServiceStub):
    async def stream_frames(
        self,
        message: "CameraStreamRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[CameraFrame]":
        async for response in self._unary_stream(
            "/resonite_io.v1.Camera/StreamFrames",
            message,
            CameraFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class DisplayStub(betterproto2_grpclib.ServiceStub):
    async def apply(
        self,
        message: "DisplayConfig",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayState":
        return await self._unary_unary(
            "/resonite_io.v1.Display/Apply",
            message,
            DisplayState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get(
        self,
        message: "DisplayGetRequest | None" = None,
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "DisplayState":
        if message is None:
            message = DisplayGetRequest()

        return await self._unary_unary(
            "/resonite_io.v1.Display/Get",
            message,
            DisplayState,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class LocomotionStub(betterproto2_grpclib.ServiceStub):
    async def drive(
        self,
        messages: "AsyncIterable[LocomotionCommand] | Iterable[LocomotionCommand]",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御を 1 本の client-streaming RPC に集約。
        同時 Drive ポリシーは accept-overwrite (両方を受け付け Bridge の latest-wins
        に委ねる)。
        """

        return await self._stream_unary(
            "/resonite_io.v1.Locomotion/Drive",
            messages,
            LocomotionCommand,
            LocomotionDriveSummary,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SessionStub(betterproto2_grpclib.ServiceStub):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(
        self,
        message: "PingRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "PingResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Session/Ping",
            message,
            PingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CameraBase(betterproto2_grpclib.ServiceBase):
    async def stream_frames(
        self, message: "CameraStreamRequest"
    ) -> "AsyncIterator[CameraFrame]":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield CameraFrame()

    async def __rpc_stream_frames(
        self, stream: "grpclib.server.Stream[CameraStreamRequest, CameraFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_frames,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Camera/StreamFrames": grpclib.const.Handler(
                self.__rpc_stream_frames,
                grpclib.const.Cardinality.UNARY_STREAM,
                CameraStreamRequest,
                CameraFrame,
            ),
        }


class DisplayBase(betterproto2_grpclib.ServiceBase):
    async def apply(self, message: "DisplayConfig") -> "DisplayState":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get(self, message: "DisplayGetRequest") -> "DisplayState":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_apply(
        self, stream: "grpclib.server.Stream[DisplayConfig, DisplayState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.apply(request)
        await stream.send_message(response)

    async def __rpc_get(
        self, stream: "grpclib.server.Stream[DisplayGetRequest, DisplayState]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.get(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Display/Apply": grpclib.const.Handler(
                self.__rpc_apply,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayConfig,
                DisplayState,
            ),
            "/resonite_io.v1.Display/Get": grpclib.const.Handler(
                self.__rpc_get,
                grpclib.const.Cardinality.UNARY_UNARY,
                DisplayGetRequest,
                DisplayState,
            ),
        }


class LocomotionBase(betterproto2_grpclib.ServiceBase):
    async def drive(
        self, messages: "AsyncIterator[LocomotionCommand]"
    ) -> "LocomotionDriveSummary":
        """
        移動 + 視点制御を 1 本の client-streaming RPC に集約。
        同時 Drive ポリシーは accept-overwrite (両方を受け付け Bridge の latest-wins
        に委ねる)。
        """

        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_drive(
        self, stream: "grpclib.server.Stream[LocomotionCommand, LocomotionDriveSummary]"
    ) -> None:
        request = stream.__aiter__()
        response = await self.drive(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Locomotion/Drive": grpclib.const.Handler(
                self.__rpc_drive,
                grpclib.const.Cardinality.STREAM_UNARY,
                LocomotionCommand,
                LocomotionDriveSummary,
            ),
        }


class SessionBase(betterproto2_grpclib.ServiceBase):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(self, message: "PingRequest") -> "PingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self, stream: "grpclib.server.Stream[PingRequest, PingResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.ping(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Session/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                PingRequest,
                PingResponse,
            ),
        }
