#!/usr/bin/env bash
# scripts/container-init.sh
#
# container 内 dev ユーザーで実行する冪等な deps restore レシピ。
#
# 流れ:
#   1. dotnet tool restore で .config/dotnet-tools.json を解決
#   2. python/ で uv sync --all-extras を実行
#   3. (best-effort) pre-commit install --install-hooks
#
# Usage:
#   scripts/container-init.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="container-init"
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

WORKSPACE_DIR="/workspace"

if [[ $# -gt 0 ]]; then
  die "Unknown argument(s): $* (本レシピは引数を取りません)"
fi

# ===== 1. dotnet local tools の restore =====================================
restore_dotnet_tools() {
  if [[ ! -f "$WORKSPACE_DIR/.config/dotnet-tools.json" ]]; then
    log ".config/dotnet-tools.json が無いため dotnet tool restore は skip。"
    return
  fi
  have dotnet || die "dotnet が PATH に無い。Dockerfile のインストールを確認してください。"
  log "Restoring .NET local tools..."
  (cd "$WORKSPACE_DIR" && dotnet tool restore)
}

# ===== 2. uv sync ============================================================
sync_python() {
  if [[ ! -f "$WORKSPACE_DIR/python/pyproject.toml" ]]; then
    log "python/pyproject.toml が無いため uv sync は skip。"
    return
  fi
  have uv || die "uv が PATH に無い。Dockerfile のインストールを確認してください。"
  log "Running uv sync --all-extras (python/)..."
  (cd "$WORKSPACE_DIR/python" && uv sync --all-extras)

  # uv tool install --editable は uv.lock を無視して fresh resolve するため
  # betterproto2 / compiler の version skew で ImportError を起こす。代わりに
  # ~/.local/bin/resoio を wrapper script として書き、uv-managed venv に
  # ルーティングして lock 固定の deps を使う (argcomplete の register-python-
  # argcomplete も PATH 上の `resoio` をこの wrapper として拾える)。
  log "Installing resoio CLI wrapper at \$HOME/.local/bin/resoio..."
  install -d "$HOME/.local/bin"
  cat >"$HOME/.local/bin/resoio" <<'WRAPPER'
#!/usr/bin/env bash
# Auto-generated by scripts/container-init.sh. Routes the `resoio` CLI through
# the project's uv-managed venv so betterproto2 stays version-locked with the
# compiled stubs in python/src/resoio/_generated/.
# PYTHON_ARGCOMPLETE_OK
exec uv run --project /workspace/python resoio "$@"
WRAPPER
  chmod 755 "$HOME/.local/bin/resoio"
}

# ===== 3. pre-commit install (best-effort) ==================================
install_pre_commit_hooks() {
  if [[ ! -f "$WORKSPACE_DIR/.pre-commit-config.yaml" ]]; then
    log ".pre-commit-config.yaml が無いため pre-commit install は skip。"
    return
  fi
  if ! have pre-commit; then
    log "pre-commit が未インストール。uv tool install pre-commit を試行 (best-effort)。"
    if ! uv tool install pre-commit; then
      warn "pre-commit のインストールに失敗。hook 登録を skip して続行します。"
      return
    fi
  fi
  log "Installing pre-commit git hooks..."
  if ! (cd "$WORKSPACE_DIR" && pre-commit install --install-hooks); then
    warn "pre-commit install に失敗。hook 登録を skip して続行します。"
    return
  fi
}

main() {
  log "Resolving dependencies in $WORKSPACE_DIR"
  restore_dotnet_tools
  sync_python
  install_pre_commit_hooks
  log "Done. 'just --list' で利用可能レシピを確認してください。"
}

main "$@"
