#!/usr/bin/env python3
"""Generate Codex rules from Claude settings.

This script is intentionally narrow: it only translates deterministic
`Bash(...)` entries from `.claude/settings*.json` into Codex `prefix_rule`
entries. Skills, agents, and prose guidance need human judgment and belong in
the `migrate-claude` skill workflow.
"""

from __future__ import annotations

import argparse
import json
import shlex
import sys
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import TypeAlias


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATHS = (
    ROOT / ".claude" / "settings.json",
    ROOT / ".claude" / "settings.container.json",
)
RULES_PATH = ROOT / ".codex" / "rules" / "default.rules"

PatternItem: TypeAlias = str | list[str]


@dataclass(frozen=True)
class PermissionRule:
    pattern: tuple[PatternItem, ...]
    decision: str
    sources: tuple[str, ...]


def load_claude_permissions() -> tuple[list[str], list[str], list[str]]:
    shell_allow: set[str] = set()
    shell_deny: set[str] = set()
    non_shell: set[str] = set()

    for path in SOURCE_PATHS:
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        permissions = data.get("permissions", {})
        collect_permissions(permissions.get("allow", []), shell_allow, non_shell)
        collect_permissions(permissions.get("deny", []), shell_deny, non_shell)

    return sorted(shell_allow), sorted(shell_deny), sorted(non_shell)


def collect_permissions(
    values: object,
    shell_permissions: set[str],
    non_shell_permissions: set[str],
) -> None:
    if not isinstance(values, list):
        return
    for value in values:
        if not isinstance(value, str):
            continue
        if value.startswith("Bash(") and value.endswith(")"):
            shell_permissions.add(value)
        else:
            non_shell_permissions.add(value)


def generate_rules() -> str:
    shell_allow, shell_deny, non_shell = load_claude_permissions()
    rules = [
        *build_rules(shell_deny, decision="forbidden"),
        *build_rules(shell_allow, decision="allow"),
    ]
    header = [
        "# Generated by scripts/migrate_codex.py from .claude/settings*.json.",
        "#",
        "# This generator only performs formal Bash permission migration.",
        "# Migrate Claude skills, agents, docs, and prose with the migrate-claude skill.",
        f"# Source summary: {len(shell_allow)} shell allow rule(s), {len(shell_deny)} shell deny rule(s).",
        "# Non-shell Claude permissions are handled by Codex tools/sandbox instead:",
        f"# {', '.join(non_shell) if non_shell else 'none'}",
        "",
    ]
    body = "\n\n".join(render_rule(rule) for rule in rules)
    return "\n".join(header) + "\n" + body + "\n"


def build_rules(sources: list[str], decision: str) -> list[PermissionRule]:
    expanded: dict[tuple[str, ...], set[str]] = {}
    for source in sources:
        for prefix in expand_permission(source):
            expanded.setdefault(prefix, set()).add(source)

    compacted = remove_redundant_prefixes(expanded)
    return group_prefixes(compacted, decision=decision)


def expand_permission(source: str) -> list[tuple[str, ...]]:
    command = source.removeprefix("Bash(").removesuffix(")")
    if command.endswith(":*"):
        command = command[:-2]
    tokens = [token for token in shlex.split(command) if token != "*"]
    if not tokens:
        return []

    prefixes: list[tuple[str, ...]] = [()]
    for token in tokens:
        expanded_tokens = expand_glob_token(token)
        prefixes = [
            (*prefix, expanded_token)
            for prefix in prefixes
            for expanded_token in expanded_tokens
        ]
    return prefixes


def expand_glob_token(token: str) -> list[str]:
    if "*" not in token:
        return [token]
    matches = sorted(
        path.relative_to(ROOT).as_posix() for path in ROOT.glob(token) if path.is_file()
    )
    return matches or [token]


def remove_redundant_prefixes(
    expanded: dict[tuple[str, ...], set[str]],
) -> dict[tuple[str, ...], set[str]]:
    compacted: dict[tuple[str, ...], set[str]] = {}
    for prefix in sorted(expanded, key=lambda item: (len(item), item)):
        covering = next(
            (
                existing
                for existing in compacted
                if len(existing) <= len(prefix) and prefix[: len(existing)] == existing
            ),
            None,
        )
        if covering is None:
            compacted[prefix] = set(expanded[prefix])
        else:
            compacted[covering].update(expanded[prefix])
    return compacted


def group_prefixes(
    compacted: dict[tuple[str, ...], set[str]],
    decision: str,
) -> list[PermissionRule]:
    rules: list[PermissionRule] = []
    remaining = dict(compacted)

    simple = sorted(prefix[0] for prefix in remaining if len(prefix) == 1)
    if simple:
        sources = collect_sources(remaining.pop((command,)) for command in simple)
        rules.append(
            PermissionRule(
                pattern=(simple,),
                decision=decision,
                sources=sources,
            )
        )

    grouped: dict[str, list[tuple[str, ...]]] = {}
    for prefix in remaining:
        grouped.setdefault(prefix[0], []).append(prefix)

    for command, prefixes in sorted(grouped.items()):
        two_part = [prefix for prefix in prefixes if len(prefix) == 2]
        if len(two_part) == len(prefixes):
            subcommands = sorted(prefix[1] for prefix in two_part)
            sources = collect_sources(remaining[prefix] for prefix in two_part)
            rules.append(
                PermissionRule(
                    pattern=(command, subcommands),
                    decision=decision,
                    sources=sources,
                )
            )
            continue

        for prefix in sorted(prefixes):
            rules.append(
                PermissionRule(
                    pattern=prefix,
                    decision=decision,
                    sources=tuple(sorted(remaining[prefix])),
                )
            )

    return rules


def collect_sources(source_groups: Iterable[Iterable[str]]) -> tuple[str, ...]:
    sources: set[str] = set()
    for source_group in source_groups:
        sources.update(source_group)
    return tuple(sorted(sources))


def render_rule(rule: PermissionRule) -> str:
    source_comment = ", ".join(rule.sources)
    lines = [
        f"# Source: {source_comment}",
        "prefix_rule(",
        render_assignment("pattern", list(rule.pattern)),
        render_assignment("decision", rule.decision),
        render_assignment(
            "justification",
            f"Migrated from Claude {rule.decision} permission.",
        ),
        render_assignment("match", [example_command(rule.pattern)]),
        ")",
    ]
    return "\n".join(lines)


def render_assignment(name: str, value: object) -> str:
    rendered = render_value(value, indent=4)
    return f"    {name} = {rendered},"


def render_value(value: object, indent: int) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        if not value:
            return "[]"
        if all(isinstance(item, str) for item in value) and len(value) <= 4:
            return "[" + ", ".join(render_value(item, indent) for item in value) + "]"

        child_indent = indent + 4
        lines = ["["]
        for item in value:
            lines.append(f"{' ' * child_indent}{render_value(item, child_indent)},")
        lines.append(f"{' ' * indent}]")
        return "\n".join(lines)
    raise TypeError(f"Unsupported rule value: {value!r}")


def example_command(pattern: tuple[PatternItem, ...]) -> str:
    tokens = [item[0] if isinstance(item, list) else item for item in pattern]
    return " ".join(tokens)


def write_rules(check: bool) -> bool:
    content = generate_rules()
    old = RULES_PATH.read_text(encoding="utf-8") if RULES_PATH.exists() else None
    changed = old != content
    if changed and not check:
        RULES_PATH.parent.mkdir(parents=True, exist_ok=True)
        RULES_PATH.write_text(content, encoding="utf-8")
    return changed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Codex rules from .claude/settings*.json.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated Codex rules are stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    changed = write_rules(check=args.check)
    if changed:
        action = "would update" if args.check else "updated"
        print(f"{action}: {RULES_PATH.relative_to(ROOT)}")
        return 1 if args.check else 0
    print(f"Codex rules are up to date: {RULES_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
